/* Generated by scripts/build_reinvent_page.py -- do not edit by hand. */
(function () {
  "use strict";
  var CFG = window.RI_CONFIG, DATA = null;
  var PAGE_SIZE = 60, shown = PAGE_SIZE;
  var PLAN_KEY = "ri2026.plan", TUNE_KEY = "ri2026.travel";
  var CATALOG_URL = "https://registration.awsevents.com/flow/awsevents/"
                  + "reinvent2026/eventcatalog/page/eventcatalog";

  var state = { lane: "all", q: "", day: "", type: "", level: "",
                venue: "", service: "" };
  var plan = load(PLAN_KEY, []);
  var tune = load(TUNE_KEY, null) || {
    overhead: CFG.travel.overhead, pace: CFG.travel.pace };
  if (tune.pace == null || tune.overhead == null) {      // an old saved shape
    tune = { overhead: CFG.travel.overhead, pace: CFG.travel.pace };
  }

  function load(key, dflt) {
    try { var v = JSON.parse(localStorage.getItem(key)); return v || dflt; }
    catch (e) { return dflt; }
  }
  function save(key, value) {
    try { localStorage.setItem(key, JSON.stringify(value)); } catch (e) {}
  }
  function $(sel) { return document.querySelector(sel); }
  function el(tag, cls, text) {
    var n = document.createElement(tag);
    if (cls) n.className = cls;
    if (text != null) n.textContent = text;
    return n;
  }
  function km(m) {
    return m >= 1000 ? (m / 1000).toFixed(1) + " km" : m + " m";
  }

  function hhmm(min) {
    var h = Math.floor(min / 60), m = min % 60;
    return (h < 10 ? "0" : "") + h + ":" + (m < 10 ? "0" : "") + m;
  }
  function dayLabel(iso) {
    var d = new Date(iso + "T12:00:00");
    return d.toLocaleDateString(undefined,
      { weekday: "long", day: "numeric", month: "long" });
  }

  /* ---- the venue-hop rule -------------------------------------------
     The gap is a fact from AWS's own times. The distance is a fact from
     the venues' coordinates. Only the PACE is an assumption, and it is
     the one thing exposed as a control -- so the estimate is arithmetic
     on two facts and one number the reader owns. */
  function metresBetween(a, b) {
    var row = CFG.travel.matrix[a];
    return row && row[b] ? row[b].m : 0;
  }

  function needFor(fromVenue, toVenue) {
    var m = metresBetween(fromVenue, toVenue);
    if (!m) return tune.overhead;
    return tune.overhead
         + Math.round(m * CFG.travel.detour / tune.pace);
  }

  /* ---- data --------------------------------------------------------- */
  function firstSlot(s) { return s.when && s.when.length ? s.when[0] : null; }
  function svcNames(s) {
    return s.sv.map(function (i) { return DATA.facets.Services[i]; });
  }
  function typeName(s) {
    return s.ty == null ? "" : DATA.facets.Type[s.ty];
  }
  function levelName(s) {
    return s.lv == null ? "" : DATA.facets.Level[s.lv];
  }
  function venueName(slot) { return DATA.venues[slot.v]; }
  function roomName(slot) { return DATA.rooms[slot.r]; }

  function laneServices(id) {
    for (var i = 0; i < CFG.lanes.length; i++)
      if (CFG.lanes[i].id === id) return CFG.lanes[i].services;
    return null;
  }

  function matches(s) {
    if (state.lane !== "all") {
      var want = laneServices(state.lane), hit = false;
      for (var i = 0; i < s.sv.length && !hit; i++)
        if (want.indexOf(s.sv[i]) !== -1) hit = true;
      if (!hit) return false;
    }
    if (state.type && typeName(s) !== state.type) return false;
    if (state.level && levelName(s) !== state.level) return false;
    if (state.service && s.sv.indexOf(+state.service) === -1) return false;
    if (state.day || state.venue) {
      var ok = false;
      for (var j = 0; j < s.when.length && !ok; j++) {
        var w = s.when[j];
        if (state.day && w.d !== state.day) continue;
        if (state.venue && venueName(w) !== state.venue) continue;
        ok = true;
      }
      if (!ok) return false;
    }
    if (state.q) {
      var hay = (s.c + " " + s.t + " " + s.a + " " +
                 svcNames(s).join(" ")).toLowerCase();
      var terms = state.q.toLowerCase().split(/\s+/);
      for (var k = 0; k < terms.length; k++)
        if (terms[k] && hay.indexOf(terms[k]) === -1) return false;
    }
    return true;
  }

  function filtered() { return DATA.sessions.filter(matches); }

  /* ---- rendering ----------------------------------------------------- */
  function card(s, slot) {
    var c = el("article", "card");
    c.dataset.code = s.c;

    var top = el("div", "top");
    /* The code is the link. ?search=<code> was verified against a control:
       the /sessionDetails?sessionId= form silently falls back to the full
       catalog list, which looks like it worked. This one resolves, and the
       code is stable and human-readable where the internal id is neither. */
    var code = el("a", "code", s.c);
    code.href = CATALOG_URL + "?search=" + encodeURIComponent(s.c);
    code.target = "_blank";
    code.rel = "noopener";
    code.title = "Open " + s.c + " in the official AWS catalog";
    top.appendChild(code);
    if (typeName(s)) top.appendChild(el("span", "tag", typeName(s)));
    if (levelName(s)) top.appendChild(el("span", "tag lvl", levelName(s)));
    if (slot && slot.e != null) {
      top.appendChild(el("span", "tag",
        hhmm(slot.b) + "–" + hhmm(slot.e)));
    } else if (slot) {
      /* AWS publishes a start and no duration for a few sponsored
         sessions. Saying so beats inventing an end time. */
      top.appendChild(el("span", "tag",
        hhmm(slot.b) + " · length not published"));
    } else {
      top.appendChild(el("span", "tag", "not yet scheduled"));
    }
    c.appendChild(top);

    c.appendChild(el("h3", null, s.t));

    var where = el("div", "where");
    if (slot) {
      var b = el("b", null, venueName(slot));
      where.appendChild(b);
      var rest = roomName(slot).split("|").slice(1).join(" · ").trim();
      where.appendChild(document.createTextNode(
        (rest ? " · " + rest : "") +
        (slot.cap ? " · " + slot.cap + " seats" : "")));
    } else {
      where.textContent = "Venue to be announced";
    }
    c.appendChild(where);

    var star = el("button", "star", inPlan(s.c) ? "★" : "☆");
    star.setAttribute("aria-pressed", inPlan(s.c) ? "true" : "false");
    star.title = inPlan(s.c) ? "Remove from my plan" : "Add to my plan";
    star.addEventListener("click", function () { toggle(s.c); });
    c.appendChild(star);

    if (s.a) {
      var more = el("button", "more", "What is in it ›");
      var abs = el("p", "abstract", s.a);
      if (svcNames(s).length)
        abs.appendChild(el("span", null, "\n\nServices: " +
          svcNames(s).join(", ")));
      more.addEventListener("click", function () {
        c.classList.toggle("open");
        more.textContent = c.classList.contains("open")
          ? "Hide ‹" : "What is in it ›";
      });
      c.appendChild(more);
      c.appendChild(abs);
    }
    return c;
  }

  function renderBrowse() {
    var box = $("#browse");
    box.textContent = "";
    var list = filtered();

    $("#count").innerHTML = "<b>" + list.length.toLocaleString() +
      "</b> session" + (list.length === 1 ? "" : "s") +
      (state.lane === "all" ? "" : " in " + laneName(state.lane));

    if (!list.length) {
      box.appendChild(el("p", "empty",
        "Nothing matches. Try clearing a filter."));
      return;
    }

    /* One row per scheduled slot, so a repeated session appears on each
       day it actually runs -- which is the thing you are choosing between. */
    var rows = [];
    list.forEach(function (s) {
      if (!s.when.length) { rows.push({ s: s, w: null, d: "zzz" }); return; }
      s.when.forEach(function (w) {
        if (state.day && w.d !== state.day) return;
        if (state.venue && venueName(w) !== state.venue) return;
        rows.push({ s: s, w: w, d: w.d });
      });
    });
    rows.sort(function (a, b) {
      if (a.d !== b.d) return a.d < b.d ? -1 : 1;
      if (!a.w || !b.w) return a.w ? -1 : 1;
      return a.w.b - b.w.b;
    });

    var slice = rows.slice(0, shown), group = null, host = null;
    slice.forEach(function (r) {
      if (r.d !== group) {
        group = r.d;
        var g = el("section", "daygroup");
        g.appendChild(el("h2", "dayhead",
          r.w ? dayLabel(r.d) : "Not yet scheduled"));
        box.appendChild(g);
        host = g;
      }
      host.appendChild(card(r.s, r.w));
    });

    if (rows.length > shown) {
      var pager = el("div", "pager");
      var btn = el("button", "ghost",
        "Show " + Math.min(PAGE_SIZE, rows.length - shown) + " more of " +
        (rows.length - shown).toLocaleString());
      btn.addEventListener("click", function () {
        shown += PAGE_SIZE; renderBrowse();
      });
      pager.appendChild(btn);
      box.appendChild(pager);
    }
  }


  /* ---- the live check -------------------------------------------------
     The snapshot is what makes this page fast and usable on conference
     wifi; it is not what makes it true. On load the page asks the catalog
     itself -- one request -- how many sessions it currently has, and says
     so if that disagrees with the copy being shown.

     Measured 2026-09-22 before building this: the catalog reflects any
     Origin back in Access-Control-Allow-Origin, its preflight names
     rfApiProfileId and rfWidgetId in Access-Control-Allow-Headers, and a
     real browser on another origin fetched all 1,582 sessions. So this
     needs no proxy and no server.

     Every failure path is silent and falls back to the snapshot, because
     the snapshot is already correct and a red banner about a CORS error
     helps nobody standing in a corridor. The only thing a failure costs
     is the live confirmation, and the age line still tells the truth.

     One request, not thirty-two: counting is cheap, and pulling the whole
     catalog on every page view would be rude to AWS and slow for the
     reader. The full pull happens only if they ask for it. */
  var live = { state: "idle", total: null, checkedAt: null };

  function liveHeaders() {
    var api = DATA.api;
    if (!api || !api.headers) return null;
    var h = { "Content-Type":
                "application/x-www-form-urlencoded; charset=UTF-8" };
    for (var k in api.headers) if (api.headers.hasOwnProperty(k))
      h[k] = api.headers[k];
    return h;
  }

  function liveFetch(extra) {
    var h = liveHeaders();
    if (!h) return Promise.reject(new Error("no api details in the store"));
    var body = new URLSearchParams({
      type: "session", browserTimezone: "America/Chicago",
      catalogDisplay: "list" });
    for (var k in (extra || {})) body.set(k, extra[k]);
    return fetch(DATA.api.url,
                 { method: "POST", headers: h, body: body.toString() })
      .then(function (r) {
        if (!r.ok) throw new Error("HTTP " + r.status);
        return r.json();
      });
  }

  function checkLive() {
    if (!DATA.api) return;
    live.state = "checking";
    liveFetch().then(function (d) {
      var total = parseInt(d.totalSearchItems, 10);
      if (isNaN(total)) throw new Error("no total in the response");
      live.total = total;
      live.checkedAt = Date.now();
      live.state = (total === DATA.sessions.length) ? "same" : "drift";
      renderFreshness();
    }).catch(function () {
      /* Silent on purpose. The snapshot stands, and the age line already
         tells the reader how old it is. */
      live.state = "unreachable";
      renderFreshness();
    });
  }

  function pullLive() {
    var btn = $("#live-pull");
    if (btn) { btn.disabled = true; btn.textContent = "Loading…"; }
    var all = [], PAGE = 50;

    function items(d) {
      if (d.items && d.items.length) return d.items;
      var sl = d.sectionList || [];
      return sl.length ? (sl[0].items || []) : [];
    }
    var expected = 0;

    /* Paced, because the catalog throttles a burst. Without the pause this
       stopped dead after two pages and handed back 100 sessions -- and the
       page then displayed those 100 as "live data", having thrown away a
       complete snapshot for a partial pull. That is the same failure the
       fetcher's shrink guard exists to prevent, so it gets the same
       answer: reconcile against the catalog's own total, and if the pull
       is short, keep the snapshot and say the pull failed. */
    function page(from) {
      return liveFetch(from ? { from: String(from) } : null)
        .then(function (d) {
          var got = items(d);
          all = all.concat(got);
          expected = parseInt(d.totalSearchItems, 10) || expected;
          if (got.length && all.length < expected)
            return new Promise(function (go) { setTimeout(go, 250); })
              .then(function () { return page(from + PAGE); });
          return all;
        });
    }
    page(0).then(function (raw) {
      if (!expected || raw.length < expected) {
        throw new Error("short pull: " + raw.length + " of " + expected);
      }
      DATA = reslim(raw, DATA);
      live.state = "live";
      live.checkedAt = Date.now();
      buildFilters();
      renderFreshness();
      render();
      if (!$("#plan").hidden) renderPlan();
      if (!$("#map").hidden) { fillMapDays(); renderMap(); }
    }).catch(function () {
      /* The snapshot is untouched and still on screen. */
      live.state = "pullfailed";
      renderFreshness();
    });
  }

  /* The browser's own copy of the slimming the fetcher does, so live data
     and stored data are exactly the same shape downstream. Facet tables are
     rebuilt from scratch rather than reusing the snapshot's, because an
     index into the wrong table renders as the wrong service name -- which
     would look like data rather than like a bug. */
  function reslim(raw, prev) {
    var FACETS = ["Type", "Level", "Role", "Services", "Topic",
                  "Area of Interest", "Industry"];
    var KEY = { "Type": "ty", "Level": "lv", "Role": "ro", "Services": "sv",
                "Topic": "tp", "Area of Interest": "ai", "Industry": "in" };
    var SINGLE = { "Type": 1, "Level": 1 };
    var tables = {}, venues = [], rooms = [];
    FACETS.forEach(function (f) { tables[f] = []; });

    function intern(list, v) {
      var i = list.indexOf(v);
      if (i === -1) { list.push(v); i = list.length - 1; }
      return i;
    }
    var out = raw.map(function (s) {
      var f = {};
      (s.attributevalues || []).forEach(function (av) {
        if (FACETS.indexOf(av.attribute) === -1 || !av.value) return;
        (f[av.attribute] = f[av.attribute] || []);
        if (f[av.attribute].indexOf(av.value) === -1)
          f[av.attribute].push(av.value);
      });
      var when = [];
      (s.times || []).forEach(function (t) {
        if (t.startTimeMin == null || t.endTimeMin == null) return;
        var b = t.startTimeMin | 0, e = t.endTimeMin | 0;
        var room = t.room || "";
        when.push({ d: t.date || "", b: b, e: e <= b ? null : e,
                    v: intern(venues, room.split("|")[0].trim()),
                    r: intern(rooms, room),
                    cap: /^\d+$/.test(String(t.capacity)) ? +t.capacity : null });
      });
      var rec = { c: s.code || "", t: (s.title || "").trim(),
                  a: (s.abstract || "").replace(/\s+/g, " ").trim(),
                  len: s.length ? (s.length | 0) : null, when: when };
      FACETS.forEach(function (name) {
        var idx = (f[name] || []).map(function (v) {
          return intern(tables[name], v); });
        rec[KEY[name]] = SINGLE[name] ? (idx.length ? idx[0] : null) : idx;
      });
      return rec;
    });

    var facets = {};
    FACETS.forEach(function (f) { facets[f] = tables[f]; });
    return { sessions: out, facets: facets, venues: venues, rooms: rooms,
             captured: prev.captured, captured_utc: prev.captured_utc,
             api: prev.api, live: true };
  }

  /* ---- how old is this, really ---------------------------------------
     Computed here rather than written in at build time, because the
     honest number is the one the reader is looking at now. A page built
     in September and opened in November has not got fresher, and a
     baked-in "captured 22 Sep" invites it to be read as if it had. */
  var AGING_DAYS = 10, STALE_DAYS = 21;

  function daysSince(iso) {
    if (!iso) return null;
    var then = new Date(iso);
    if (isNaN(then.getTime())) return null;
    return Math.floor((Date.now() - then.getTime()) / 86400000);
  }

  function renderFreshness() {
    var box = $("#fresh");
    var age = daysSince(DATA.captured_utc || DATA.captured);
    var when = DATA.captured || "an unrecorded date";
    box.textContent = "";

    /* Pulled live this session: the snapshot's age is no longer the
       interesting number, so it stops being the headline. */
    if (live.state === "live") {
      box.className = "fresh good";
      box.appendChild(el("b", null, "Showing live data"));
      box.appendChild(el("span", null,
        ", pulled from the AWS catalog a moment ago — "
        + DATA.sessions.length.toLocaleString() + " sessions. Seat "
        + "reservations still live in the "));
      addCatalogLink(box);
      return;
    }

    if (age === null) {
      box.className = "fresh stale";
      box.appendChild(el("span", null,
        "This copy of the catalog carries no capture date, so there is no "
        + "way to tell how old it is. Treat every time and room here as "
        + "unconfirmed and check the official catalog."));
      addCatalogLink(box);
      return;
    }

    var howLong = age === 0 ? "earlier today"
                : age === 1 ? "yesterday"
                : age + " days ago";
    var b = el("b", null, "Catalog checked " + howLong);
    box.appendChild(b);

    if (age >= STALE_DAYS) {
      box.className = "fresh stale";
      box.appendChild(el("span", null,
        " (" + when + "). That is old enough that sessions have probably "
        + "been added, moved or cancelled since. Confirm anything you are "
        + "relying on — every card links to its entry in the "));
      addCatalogLink(box);
    } else if (age >= AGING_DAYS) {
      box.className = "fresh aging";
      box.appendChild(el("span", null,
        " (" + when + "). Sessions move as the event gets closer, so check "
        + "anything you are relying on against the "));
      addCatalogLink(box);
    } else {
      box.className = "fresh good";
      box.appendChild(el("span", null,
        " (" + when + "), against " + DATA.sessions.length.toLocaleString()
        + " sessions. Seat reservations and last-minute changes still live "
        + "in the "));
      addCatalogLink(box);
    }
    appendLive(box);
  }

  /* What the one live request found, appended to whatever the age line
     already said. Drift is the case worth shouting about: it means the
     catalog has moved under this copy, and the reader can pull it now. */
  function appendLive(box) {
    if (live.state === "drift") {
      box.className = "fresh aging";
      box.appendChild(el("span", null,
        " AWS is currently listing " + live.total.toLocaleString()
        + " sessions against this copy's "
        + DATA.sessions.length.toLocaleString() + ". "));
      var btn = el("button", "livebtn", "Load the live catalog");
      btn.id = "live-pull";
      btn.addEventListener("click", pullLive);
      box.appendChild(btn);
    } else if (live.state === "same") {
      box.appendChild(el("span", "livenote",
        " Confirmed against AWS just now — same session count."));
    } else if (live.state === "pullfailed") {
      box.className = "fresh aging";
      box.appendChild(el("span", null,
        " The live catalog did not come back complete, so this is still "
        + "the stored copy rather than a half-loaded one. "));
      var again = el("button", "livebtn", "Try again");
      again.id = "live-pull";
      again.addEventListener("click", pullLive);
      box.appendChild(again);
    } else if (live.state === "unreachable") {
      box.appendChild(el("span", "livenote",
        " (Could not reach AWS to confirm just now; showing the stored "
        + "copy.)"));
    }
  }

  function addCatalogLink(box) {
    var a = el("a", null, "official catalog");
    a.href = CATALOG_URL;
    a.target = "_blank";
    a.rel = "noopener";
    box.appendChild(a);
    box.appendChild(document.createTextNode("."));
  }

  /* The whole cost table, visible. A number a reader cannot inspect is a
     number they have to take on faith, and this one changes their day. */
  function renderMatrix() {
    var host = $("#matrix");
    if (!host) return;
    var names = Object.keys(CFG.travel.matrix).sort();
    var t = el("table", "mx");
    var head = el("tr");
    head.appendChild(el("th", null, ""));
    names.forEach(function (n) { head.appendChild(el("th", null, n)); });
    t.appendChild(head);
    names.forEach(function (a) {
      var tr = el("tr");
      tr.appendChild(el("th", null, a));
      names.forEach(function (b) {
        var td = el("td");
        if (a === b) {
          td.textContent = tune.overhead + " min";
          td.className = "self";
        } else {
          var m = CFG.travel.matrix[a][b].m;
          td.appendChild(el("span", "mn", needFor(a, b) + " min"));
          td.appendChild(el("span", "md", km(m)));
        }
        tr.appendChild(td);
      });
      t.appendChild(tr);
    });
    host.textContent = "";
    host.appendChild(t);
  }


  /* ---- the map -------------------------------------------------------
     Drawn from the venues' real coordinates, to scale, with a bar showing
     what the scale is. It is rotated a quarter turn so the Strip runs
     left to right instead of producing a column 3.4 times taller than it
     is wide -- north is marked, because a map that silently reorients the
     world is worse than no map.

     No Google Maps embed, deliberately. A traffic layer here would be
     showing CAR congestion on Las Vegas Boulevard, which is not how
     anyone moves between these venues: it is walking, the conference
     shuttle and the monorail. It would look authoritative and mean
     nothing. Each hop instead links out to Google Maps for a real routed
     walking time, which costs no API key and opens the app already on
     the reader's phone. */
  var MAP_W = 1000;

  function mapH() {
    return Math.round(MAP_W * CFG.map.span_x_m / CFG.map.span_y_m);
  }

  /* geo (x=east/west, y=north/south) -> screen, quarter-turned */
  function project(v) {
    var p = CFG.map.pos[v];
    return { x: p[1] * MAP_W, y: p[0] * mapH() };
  }

  function svgEl(tag, attrs) {
    var n = document.createElementNS("http://www.w3.org/2000/svg", tag);
    for (var k in attrs) if (attrs.hasOwnProperty(k))
      n.setAttribute(k, attrs[k]);
    return n;
  }

  function mapsLink(a, b) {
    var pa = CFG.travel.points[a], pb = CFG.travel.points[b];
    return "https://www.google.com/maps/dir/?api=1"
         + "&origin=" + pa[0] + "," + pa[1]
         + "&destination=" + pb[0] + "," + pb[1]
         + "&travelmode=walking";
  }

  /* Padding is derived, not guessed. The biggest circle can reach r=39 and
     its label sits 18px below that, so a venue sitting on the edge of the
     plot -- Wynn/Encore does, it is the northern end -- needs room for both
     or it gets clipped off the corner. It was. */
  var R_MAX = 39, LABEL_DROP = 22, SCALE_BAND = 34;

  function renderMap() {
    var host = $("#mapsvg");
    if (!host) return;
    var H = mapH();
    var padX = 84, padT = 34 + R_MAX, padB = R_MAX + LABEL_DROP + SCALE_BAND;
    var names = Object.keys(CFG.map.pos);

    // How many of the CURRENTLY FILTERED sessions sit at each venue.
    // This is the heat: narrow to a lane and the map shows where that
    // lane actually lives.
    var heat = {}, total = 0;
    names.forEach(function (n) { heat[n] = 0; });
    filtered().forEach(function (s) {
      var seen = {};
      s.when.forEach(function (w) {
        var v = venueName(w);
        if (state.day && w.d !== state.day) return;
        if (seen[v]) return;
        seen[v] = 1; heat[v] += 1; total += 1;
      });
    });
    var peak = Math.max.apply(null, names.map(function (n) { return heat[n]; }));
    var nEl = $("#map-n");
    if (nEl) nEl.textContent = total.toLocaleString();

    var svg = svgEl("svg", {
      viewBox: "0 0 " + (MAP_W + padX * 2) + " " + (H + padT + padB),
      class: "rimap", role: "img",
      "aria-label": "The five re:Invent venues positioned to scale, "
        + "sized by how many matching sessions each holds."
    });
    var g = svgEl("g", { transform: "translate(" + padX + "," + padT + ")" });
    svg.appendChild(g);

    // the route for the chosen day, drawn under the venues
    var day = $("#map-day") ? $("#map-day").value : "";
    var hops = day ? routeFor(day) : [];
    hops.forEach(function (h, i) {
      var a = project(h.from), b = project(h.to);
      var line = svgEl("line", {
        x1: a.x, y1: a.y, x2: b.x, y2: b.y,
        class: "hop " + h.verdict
      });
      g.appendChild(line);
      var mx = (a.x + b.x) / 2, my = (a.y + b.y) / 2;
      var lab = svgEl("text", { x: mx, y: my - 8, class: "hoplab " + h.verdict,
                                "text-anchor": "middle" });
      lab.textContent = (i + 1) + ". " + h.gapText;
      g.appendChild(lab);
    });

    names.forEach(function (n) {
      var p = project(n);
      var frac = peak ? heat[n] / peak : 0;
      var r = 9 + Math.round(Math.sqrt(frac) * 30);
      var grp = svgEl("g", { class: "venue" });
      grp.appendChild(svgEl("circle", { cx: p.x, cy: p.y, r: r,
                                        class: "vdot" }));
      var t1 = svgEl("text", { x: p.x, y: p.y + 4, class: "vnum",
                               "text-anchor": "middle" });
      t1.textContent = heat[n];
      grp.appendChild(t1);
      var t2 = svgEl("text", { x: p.x, y: p.y + r + 18, class: "vname",
                               "text-anchor": "middle" });
      t2.textContent = n;
      grp.appendChild(t2);
      g.appendChild(grp);
    });

    // scale bar: 500 m, so the distances are readable rather than implied
    var perM = MAP_W / CFG.map.span_y_m;
    var barLen = Math.round(500 * perM);
    var by = H + R_MAX + LABEL_DROP + 14;
    g.appendChild(svgEl("line", { x1: 0, y1: by, x2: barLen, y2: by,
                                  class: "scalebar" }));
    var st = svgEl("text", { x: 0, y: by - 6, class: "scaletxt" });
    st.textContent = "500 m";
    g.appendChild(st);

    var nt = svgEl("text", { x: 0, y: -(R_MAX + 12), class: "scaletxt" });
    nt.textContent = "← north (Wynn/Encore end)    south (MGM Grand) →";
    g.appendChild(nt);

    host.textContent = "";
    host.appendChild(svg);
    renderHops(hops);
  }

  /* The day's hops, reusing exactly the plan's own feasibility rule so the
     map and the plan can never disagree with each other. */
  function routeFor(day) {
    var rows = planRows().filter(function (r) {
      return r.d === day && r.w;
    });
    var out = [];
    for (var i = 1; i < rows.length; i++) {
      var a = rows[i - 1], b = rows[i];
      var from = venueName(a.w), to = venueName(b.w);
      if (a.w.e == null) {
        out.push({ from: from, to: to, verdict: "warn", a: a, b: b,
                   gapText: "end time not published" });
        continue;
      }
      var gap = b.w.b - a.w.e, need = needFor(from, to);
      var verdict = gap < 0 ? "bad" : gap < need ? "warn" : "ok";
      out.push({ from: from, to: to, verdict: verdict, a: a, b: b,
                 gap: gap, need: need,
                 gapText: gap < 0 ? "overlap" : gap + " min / needs " + need });
    }
    return out;
  }

  function renderHops(hops) {
    var host = $("#maphops");
    if (!host) return;
    host.textContent = "";
    if (!hops.length) return;
    hops.forEach(function (h, i) {
      var row = el("div", "hoprow " + h.verdict);
      row.appendChild(el("span", "hopn", String(i + 1)));
      var txt = el("span", "hopt");
      txt.textContent = h.from + " → " + h.to
        + (h.from === h.to ? " (same property)"
           : "  ·  " + km(metresBetween(h.from, h.to)) + "  ·  "
             + h.gapText);
      row.appendChild(txt);
      if (h.from !== h.to) {
        var a = el("a", "hoplink", "walking route ↗");
        a.href = mapsLink(h.from, h.to);
        a.target = "_blank"; a.rel = "noopener";
        a.title = "Open this hop in Google Maps for a live routed time";
        row.appendChild(a);
      }
      host.appendChild(row);
    });
  }

  function fillMapDays() {
    var sel = $("#map-day");
    if (!sel) return;
    var have = {};
    planRows().forEach(function (r) { if (r.w) have[r.d] = 1; });
    var keep = sel.value;
    sel.textContent = "";
    sel.appendChild(new Option("— no day selected —", ""));
    CFG.days.forEach(function (d) {
      if (have[d]) sel.appendChild(new Option(dayLabel(d), d));
    });
    sel.value = have[keep] ? keep : "";
    sel.onchange = renderMap;
  }

  function laneName(id) {
    for (var i = 0; i < CFG.lanes.length; i++)
      if (CFG.lanes[i].id === id) return CFG.lanes[i].name;
    return id;
  }

  /* ---- the plan ------------------------------------------------------ */
  function inPlan(code) { return plan.indexOf(code) !== -1; }
  function toggle(code) {
    var i = plan.indexOf(code);
    if (i === -1) plan.push(code); else plan.splice(i, 1);
    save(PLAN_KEY, plan);
    syncStars(); renderPlan();
    if (!$("#map").hidden) { fillMapDays(); renderMap(); }
  }
  function syncStars() {
    $("#planN").textContent = plan.length;
    Array.prototype.forEach.call(
      document.querySelectorAll(".card"), function (c) {
        var on = inPlan(c.dataset.code), b = c.querySelector(".star");
        if (!b) return;
        b.textContent = on ? "★" : "☆";
        b.setAttribute("aria-pressed", on ? "true" : "false");
        b.title = on ? "Remove from my plan" : "Add to my plan";
      });
  }

  function planRows() {
    var by = {}, rows = [];
    DATA.sessions.forEach(function (s) { by[s.c] = s; });
    plan.forEach(function (code) {
      var s = by[code];
      if (!s) {
        /* The session is starred and is no longer in the catalog. Dropping
           it silently was the worst thing this page could do: the plan
           would simply be one session shorter than the person built, with
           nothing to say a talk they were counting on has gone. */
        rows.push({ gone: code, d: "zzzz" });
        return;
      }
      if (!s.when.length) { rows.push({ s: s, w: null, d: "zzz" }); return; }
      s.when.forEach(function (w) { rows.push({ s: s, w: w, d: w.d }); });
    });
    rows.sort(function (a, b) {
      if (a.d !== b.d) return a.d < b.d ? -1 : 1;
      if (!a.w || !b.w) return a.w ? -1 : 1;
      return a.w.b - b.w.b;
    });
    return rows;
  }

  function renderPlan() {
    var box = $("#planbody");
    box.textContent = "";
    var rows = planRows();
    if (!rows.length) {
      box.appendChild(el("p", "empty",
        "Nothing starred yet. Star a session in Browse and it lands here, "
        + "with the travel between them checked."));
      return;
    }

    var group = null, host = null, prev = null;
    rows.forEach(function (r) {
      if (r.d !== group) {
        group = r.d; prev = null;
        host = el("section", "daygroup");
        host.appendChild(el("h2", "dayhead",
          r.gone ? "No longer in the catalog"
                 : r.w ? dayLabel(r.d) : "Not yet scheduled"));
        box.appendChild(host);
      }
      if (r.gone) { host.appendChild(goneCard(r.gone)); prev = null; return; }
      if (prev && prev.w && r.w) host.appendChild(gapRow(prev, r));
      host.appendChild(card(r.s, r.w));
      prev = r;
    });
  }

  function goneCard(code) {
    var c = el("article", "card gone");
    c.dataset.code = code;
    var top = el("div", "top");
    top.appendChild(el("span", "code", code));
    top.appendChild(el("span", "tag", "withdrawn or renamed"));
    c.appendChild(top);
    c.appendChild(el("h3", null, "This session is no longer in the catalog"));
    var where = el("div", "where");
    where.appendChild(document.createTextNode(
      "You starred it, and the capture of " + (DATA.captured || "the catalog")
      + " does not contain it. AWS may have withdrawn, merged or renumbered "
      + "it. Check "));
    var a = el("a", null, code + " in the official catalog");
    a.href = CATALOG_URL + "?search=" + encodeURIComponent(code);
    a.target = "_blank"; a.rel = "noopener";
    where.appendChild(a);
    where.appendChild(document.createTextNode("."));
    c.appendChild(where);
    var drop = el("button", "star", "×");
    drop.title = "Remove it from my plan";
    drop.addEventListener("click", function () { toggle(code); });
    c.appendChild(drop);
    return c;
  }

  function gapRow(a, b) {
    var from = venueName(a.w), to = venueName(b.w);
    var need = needFor(from, to);
    var row = el("div", "gap"), msg;

    if (a.w.e == null) {
      /* No published end, so there is no gap to measure. The page says
         that rather than measuring from the start time and calling the
         result a gap -- which would under-warn on exactly the hop this
         feature exists to catch. */
      row.className = "gap warn";
      row.appendChild(el("span", "ic", "○"));
      row.appendChild(el("span", null,
        "AWS does not publish how long " + a.s.c + " runs, so the time "
        + "before " + b.s.c + " cannot be checked."
        + (from === to ? "" : " They are at different properties — "
           + from + " to " + to + " — so allow about " + need + " min.")));
      return row;
    }

    var gap = b.w.b - a.w.e;
    if (gap < 0) {
      row.className = "gap bad";
      row.appendChild(el("span", "ic", "●"));
      msg = "These overlap by " + (-gap) + " min. " +
        (from === to ? "Same property, but you cannot be in both."
                     : from + " and " + to + " at once is not possible.");
    } else if (gap < need) {
      row.className = "gap warn";
      row.appendChild(el("span", "ic", "●"));
      msg = gap + " min between them" +
        (from === to ? " inside " + from
                     : ", and they are " + km(metresBetween(from, to))
                       + " apart — " + from + " to " + to) +
        ". Allow about " + need + ". You would be late.";
    } else {
      row.className = "gap ok";
      row.appendChild(el("span", "ic", "○"));
      msg = gap + " min" +
        (from === to ? " to change rooms inside " + from
                     : " to cover the " + km(metresBetween(from, to))
                       + " from " + from + " to " + to) + ".";
    }
    row.appendChild(el("span", null, msg));
    return row;
  }

  /* ---- filters ------------------------------------------------------- */
  function buildFilters() {
    var host = $("#filters");
    host.textContent = "";

    function pick(key, label, options, valueOf) {
      var sel = el("select");
      sel.setAttribute("aria-label", label);
      sel.appendChild(new Option(label, ""));
      options.forEach(function (o) {
        sel.appendChild(new Option(o.label, o.value));
      });
      sel.value = state[key];
      sel.addEventListener("change", function () {
        state[key] = sel.value; shown = PAGE_SIZE; render();
      });
      host.appendChild(sel);
    }

    pick("day", "Any day", CFG.days.map(function (d) {
      return { label: dayLabel(d), value: d };
    }));
    pick("type", "Any format", DATA.facets.Type.map(function (t) {
      return { label: t, value: t };
    }));
    pick("level", "Any level", DATA.facets.Level.slice().sort()
      .map(function (l) { return { label: l, value: l }; }));
    pick("venue", "Any venue", DATA.venues.slice().sort()
      .map(function (v) { return { label: v, value: v }; }));

    /* Services is the long one -- 169 entries -- so it is sorted by how
       many sessions carry it, not alphabetically. The head of that list
       is what people are actually looking for. */
    var count = {};
    DATA.sessions.forEach(function (s) {
      s.sv.forEach(function (i) { count[i] = (count[i] || 0) + 1; });
    });
    var svc = Object.keys(count).map(Number).sort(function (a, b) {
      return count[b] - count[a];
    }).map(function (i) {
      return { label: DATA.facets.Services[i] + "  (" + count[i] + ")",
               value: String(i) };
    });
    pick("service", "Any service", svc);
  }

  function renderChips() {
    var host = $("#chips");
    host.textContent = "";
    var live = [];
    if (state.lane !== "all")
      live.push(["lane", laneName(state.lane)]);
    [["day", state.day && dayLabel(state.day)],
     ["type", state.type], ["level", state.level], ["venue", state.venue],
     ["service", state.service &&
       DATA.facets.Services[+state.service]]].forEach(function (p) {
      if (p[1]) live.push(p);
    });
    live.forEach(function (p) {
      var chip = el("span", "chip", p[1]);
      var x = el("button", null, "×");
      x.title = "Remove this filter";
      x.addEventListener("click", function () {
        state[p[0]] = p[0] === "lane" ? "all" : "";
        shown = PAGE_SIZE; buildFilters(); render();
      });
      chip.appendChild(x);
      host.appendChild(chip);
    });
  }

  function syncLaneTabs() {
    Array.prototype.forEach.call(
      document.querySelectorAll(".lane"), function (b) {
        b.setAttribute("aria-pressed",
          b.dataset.lane === state.lane ? "true" : "false");
      });
  }

  function render() {
    syncLaneTabs(); renderChips(); renderBrowse(); syncStars();
    $("#clear").hidden = !state.q;
    if (!$("#map").hidden) renderMap();
  }

  /* ---- wiring -------------------------------------------------------- */
  function wire() {
    Array.prototype.forEach.call(
      document.querySelectorAll(".lane"), function (b) {
        b.addEventListener("click", function () {
          state.lane = b.dataset.lane; shown = PAGE_SIZE; render();
          window.scrollTo({ top: $(".controls").offsetTop - 12,
                            behavior: "smooth" });
        });
      });

    var timer = null;
    $("#q").addEventListener("input", function (e) {
      clearTimeout(timer);
      var v = e.target.value;
      timer = setTimeout(function () {
        state.q = v.trim(); shown = PAGE_SIZE; render();
      }, 140);
    });
    $("#clear").addEventListener("click", function () {
      $("#q").value = ""; state.q = ""; shown = PAGE_SIZE; render();
    });

    $("#tab-browse").addEventListener("click", function () { view("browse"); });
    $("#tab-plan").addEventListener("click", function () { view("plan"); });
    $("#tab-map").addEventListener("click", function () { view("map"); });

    $("#share").addEventListener("click", function () {
      var url = location.origin + location.pathname +
        "#plan=" + encodeURIComponent(plan.join(","));
      var done = function () { $("#share").textContent = "Link copied";
        setTimeout(function () {
          $("#share").textContent = "Copy a link to this plan"; }, 1800); };
      if (navigator.clipboard) navigator.clipboard.writeText(url).then(done, done);
      else { prompt("Copy this link", url); }
    });

    $("#wipe").addEventListener("click", function () {
      if (!plan.length) return;
      if (!confirm("Clear all " + plan.length + " starred sessions?")) return;
      plan = []; save(PLAN_KEY, plan); syncStars(); renderPlan();
    });

    var over = $("#t-overhead"), pace = $("#t-pace");
    over.value = tune.overhead;
    pace.value = String(tune.pace);
    over.addEventListener("change", function () {
      var v = parseInt(over.value, 10);
      if (isNaN(v) || v < 0) { over.value = tune.overhead; return; }
      tune.overhead = v; save(TUNE_KEY, tune); renderPlan(); renderMatrix();
    });
    pace.addEventListener("change", function () {
      tune.pace = parseInt(pace.value, 10) || CFG.travel.pace;
      save(TUNE_KEY, tune); renderPlan(); renderMatrix();
    });
  }

  function view(which) {
    $("#browse").hidden = which !== "browse";
    $("#plan").hidden = which !== "plan";
    $("#map").hidden = which !== "map";
    /* Search, filters and lanes drive Browse AND the map's heat, so they
       stay up for both. In the plan they are dead controls that push the
       plan below the fold -- on a phone, past it entirely. */
    var showControls = which !== "plan";
    $(".controls").hidden = !showControls;
    document.querySelector(".lanes").hidden = !showControls;
    [["#tab-browse", "browse"], ["#tab-plan", "plan"], ["#tab-map", "map"]]
      .forEach(function (p) {
        $(p[0]).setAttribute("aria-selected",
                             which === p[1] ? "true" : "false");
      });
    if (which === "plan") renderPlan();
    if (which === "map") { fillMapDays(); renderMap(); }
  }

  function adoptSharedPlan() {
    var m = /[#&]plan=([^&]*)/.exec(location.hash);
    if (!m) return false;
    var codes = decodeURIComponent(m[1]).split(",").filter(Boolean);
    if (!codes.length) return false;
    plan = codes; save(PLAN_KEY, plan);
    history.replaceState(null, "", location.pathname);
    return true;
  }

  /* ---- boot ---------------------------------------------------------- */
  fetch("/intelligence/reinvent2026.json")
    .then(function (r) {
      if (!r.ok) throw new Error("HTTP " + r.status);
      return r.json();
    })
    .then(function (d) {
      DATA = d;
      var shared = adoptSharedPlan();
      /* A shared link opened while the page is already up changes only the
         fragment, which is a same-document navigation -- no reload, so the
         boot path below never runs again. Without this, a teammate clicking
         someone's plan link from this very page sees nothing happen. */
      window.addEventListener("hashchange", function () {
        if (adoptSharedPlan()) { syncStars(); renderPlan(); view("plan"); }
      });
      var all = document.querySelector('[data-count="all"]');
      if (all) all.textContent = DATA.sessions.length.toLocaleString();
      buildFilters(); wire(); renderFreshness(); renderMatrix();
      checkLive();
      render();
      if (shared) view("plan");
    })
    .catch(function (err) {
      $("#count").textContent =
        "The session data did not load (" + err.message +
        "). The official catalog still works.";
    });
})();
