/* Generated by scripts/build_reinvent_page.py -- do not edit by hand. */
(function () {
  "use strict";
  var CFG = window.RI_CONFIG, DATA = null;
  var PAGE_SIZE = 60, shown = PAGE_SIZE;
  var PLAN_KEY = "ri2026.plan", TUNE_KEY = "ri2026.travel";
  var CATALOG_URL = "https://registration.awsevents.com/flow/awsevents/"
                  + "reinvent2026/eventcatalog/page/eventcatalog";

  var state = { lane: "all", q: "", day: "", type: "", level: "",
                venue: "", service: "" };
  var plan = load(PLAN_KEY, []);
  var tune = load(TUNE_KEY, null) || {
    overhead: CFG.travel.overhead, pace: CFG.travel.pace };
  if (tune.pace == null || tune.overhead == null) {      // an old saved shape
    tune = { overhead: CFG.travel.overhead, pace: CFG.travel.pace };
  }

  function load(key, dflt) {
    try { var v = JSON.parse(localStorage.getItem(key)); return v || dflt; }
    catch (e) { return dflt; }
  }
  function save(key, value) {
    try { localStorage.setItem(key, JSON.stringify(value)); } catch (e) {}
  }
  function $(sel) { return document.querySelector(sel); }
  function el(tag, cls, text) {
    var n = document.createElement(tag);
    if (cls) n.className = cls;
    if (text != null) n.textContent = text;
    return n;
  }
  function km(m) {
    return m >= 1000 ? (m / 1000).toFixed(1) + " km" : m + " m";
  }

  function hhmm(min) {
    var h = Math.floor(min / 60), m = min % 60;
    return (h < 10 ? "0" : "") + h + ":" + (m < 10 ? "0" : "") + m;
  }
  function dayLabel(iso) {
    var d = new Date(iso + "T12:00:00");
    return d.toLocaleDateString(undefined,
      { weekday: "long", day: "numeric", month: "long" });
  }

  /* ---- the venue-hop rule -------------------------------------------
     The gap is a fact from AWS's own times. The distance is a fact from
     the venues' coordinates. Only the PACE is an assumption, and it is
     the one thing exposed as a control -- so the estimate is arithmetic
     on two facts and one number the reader owns. */
  function metresBetween(a, b) {
    var row = CFG.travel.matrix[a];
    return row && row[b] ? row[b].m : 0;
  }

  function needFor(fromVenue, toVenue) {
    var m = metresBetween(fromVenue, toVenue);
    if (!m) return tune.overhead;
    return tune.overhead
         + Math.round(m * CFG.travel.detour / tune.pace);
  }

  /* ---- data --------------------------------------------------------- */
  function firstSlot(s) { return s.when && s.when.length ? s.when[0] : null; }
  function svcNames(s) {
    return s.sv.map(function (i) { return DATA.facets.Services[i]; });
  }
  function speakerNames(s) {
    if (!s.sp || !DATA.speakers) return [];
    return s.sp.map(function (i) { return DATA.speakers[i]; });
  }

  /* How hard is a seat, from the capacity AWS publishes. Measured across
     the catalog: Builders' sessions are 50 seats, every one of them; chalk
     talks run 70-98; breakouts 100-1000. So a small room is a real
     constraint rather than a guess -- but it is only half the story,
     because demand is published nowhere. The wording therefore says what
     is known (the room is small) and not what is not (that it will fill). */
  var TIGHT = 60, SMALL = 100;

  function seatNote(slot) {
    if (!slot || !slot.cap) return null;
    if (slot.cap <= TIGHT)
      return { cls: "seat tight", txt: slot.cap + " seats \u2014 reserve early" };
    if (slot.cap <= SMALL)
      return { cls: "seat small", txt: slot.cap + " seats" };
    return null;
  }

  function typeName(s) {
    return s.ty == null ? "" : DATA.facets.Type[s.ty];
  }
  function levelName(s) {
    return s.lv == null ? "" : DATA.facets.Level[s.lv];
  }
  function venueName(slot) { return DATA.venues[slot.v]; }
  function roomName(slot) { return DATA.rooms[slot.r]; }

  function laneServices(id) {
    for (var i = 0; i < CFG.lanes.length; i++)
      if (CFG.lanes[i].id === id) return CFG.lanes[i].services;
    return null;
  }

  function matches(s) {
    if (state.lane !== "all") {
      var want = laneServices(state.lane), hit = false;
      for (var i = 0; i < s.sv.length && !hit; i++)
        if (want.indexOf(s.sv[i]) !== -1) hit = true;
      if (!hit) return false;
    }
    if (state.type && typeName(s) !== state.type) return false;
    if (state.level && levelName(s) !== state.level) return false;
    if (state.service && s.sv.indexOf(+state.service) === -1) return false;
    if (state.day || state.venue) {
      var ok = false;
      for (var j = 0; j < s.when.length && !ok; j++) {
        var w = s.when[j];
        if (state.day && w.d !== state.day) continue;
        if (state.venue && venueName(w) !== state.venue) continue;
        ok = true;
      }
      if (!ok) return false;
    }
    if (state.q) {
      /* The room string is in here too. Every session has one -- all
         1,561 scheduled ones carry a full "Venetian | Level 2 | Ballroom
         F | Content Hub | Purple Theater" -- and without it, typing the
         name of the building you are standing in returned nothing at all.
         "MGM Grand" found 0 sessions, which is an absurd answer from a
         page whose whole subject is where things are. */
      var where = s.when.map(function (w) {
        return roomName(w); }).join(" ");
      var hay = (s.c + " " + s.t + " " + s.a + " " +
                 svcNames(s).join(" ") + " " +
                 speakerNames(s).join(" ") + " " + where).toLowerCase();
      var terms = state.q.toLowerCase().split(/\s+/);
      for (var k = 0; k < terms.length; k++)
        if (terms[k] && hay.indexOf(terms[k]) === -1) return false;
    }
    return true;
  }

  function filtered() { return DATA.sessions.filter(matches); }

  /* ---- rendering ----------------------------------------------------- */
  function card(s, slot) {
    var c = el("article", "card");
    c.dataset.code = s.c;

    var top = el("div", "top");
    /* The code is the link. ?search=<code> was verified against a control:
       the /sessionDetails?sessionId= form silently falls back to the full
       catalog list, which looks like it worked. This one resolves, and the
       code is stable and human-readable where the internal id is neither. */
    var code = el("a", "code", s.c);
    code.href = CATALOG_URL + "?search=" + encodeURIComponent(s.c);
    code.target = "_blank";
    code.rel = "noopener";
    code.title = "Open " + s.c + " in the official AWS catalog";
    top.appendChild(code);
    if (typeName(s)) top.appendChild(el("span", "tag", typeName(s)));
    if (levelName(s)) top.appendChild(el("span", "tag lvl", levelName(s)));
    if (slot && slot.e != null) {
      top.appendChild(el("span", "tag",
        hhmm(slot.b) + "–" + hhmm(slot.e)));
    } else if (slot) {
      /* AWS publishes a start and no duration for a few sponsored
         sessions. Saying so beats inventing an end time. */
      top.appendChild(el("span", "tag",
        hhmm(slot.b) + " · length not published"));
    } else {
      top.appendChild(el("span", "tag", "not yet scheduled"));
    }
    c.appendChild(top);

    c.appendChild(el("h3", null, s.t));

    var where = el("div", "where");
    if (slot) {
      var b = el("b", null, venueName(slot));
      where.appendChild(b);
      var rest = roomName(slot).split("|").slice(1).join(" · ").trim();
      where.appendChild(document.createTextNode(
        (rest ? " · " + rest : "") +
        (slot.cap ? " · " + slot.cap + " seats" : "")));
    } else {
      where.textContent = "Venue to be announced";
    }
    c.appendChild(where);

    var note = seatNote(slot);
    if (note) top.appendChild(el("span", note.cls, note.txt));

    var star = el("button", "star", inPlan(s.c) ? "★" : "☆");
    star.setAttribute("aria-pressed", inPlan(s.c) ? "true" : "false");
    star.title = inPlan(s.c) ? "Remove from my plan" : "Add to my plan";
    star.addEventListener("click", function () { toggle(s.c); });
    c.appendChild(star);

    if (s.a) {
      var more = el("button", "more", "What is in it ›");
      var abs = el("p", "abstract", s.a);
      if (svcNames(s).length)
        abs.appendChild(el("span", null, "\n\nServices: " +
          svcNames(s).join(", ")));
      if (speakerNames(s).length)
        abs.appendChild(el("span", null, "\n\nSpeakers: " +
          speakerNames(s).join("; ")));
      more.addEventListener("click", function () {
        c.classList.toggle("open");
        more.textContent = c.classList.contains("open")
          ? "Hide ‹" : "What is in it ›";
      });
      c.appendChild(more);
      c.appendChild(abs);
    }
    return c;
  }

  function renderBrowse() {
    var box = $("#browse");
    box.textContent = "";
    var list = filtered();

    $("#count").innerHTML = "<b>" + list.length.toLocaleString() +
      "</b> session" + (list.length === 1 ? "" : "s") +
      (state.lane === "all" ? "" : " in " + laneName(state.lane));

    if (!list.length) {
      box.appendChild(el("p", "empty",
        "Nothing matches. Try clearing a filter."));
      return;
    }

    /* One row per scheduled slot, so a repeated session appears on each
       day it actually runs -- which is the thing you are choosing between. */
    var rows = [];
    list.forEach(function (s) {
      if (!s.when.length) { rows.push({ s: s, w: null, d: "zzz" }); return; }
      s.when.forEach(function (w) {
        if (state.day && w.d !== state.day) return;
        if (state.venue && venueName(w) !== state.venue) return;
        rows.push({ s: s, w: w, d: w.d });
      });
    });
    rows.sort(function (a, b) {
      if (a.d !== b.d) return a.d < b.d ? -1 : 1;
      if (!a.w || !b.w) return a.w ? -1 : 1;
      return a.w.b - b.w.b;
    });

    var slice = rows.slice(0, shown), group = null, host = null;
    slice.forEach(function (r) {
      if (r.d !== group) {
        group = r.d;
        var g = el("section", "daygroup");
        g.appendChild(el("h2", "dayhead",
          r.w ? dayLabel(r.d) : "Not yet scheduled"));
        box.appendChild(g);
        host = g;
      }
      host.appendChild(card(r.s, r.w));
    });

    if (rows.length > shown) {
      var pager = el("div", "pager");
      var btn = el("button", "ghost",
        "Show " + Math.min(PAGE_SIZE, rows.length - shown) + " more of " +
        (rows.length - shown).toLocaleString());
      btn.addEventListener("click", function () {
        shown += PAGE_SIZE; renderBrowse();
      });
      pager.appendChild(btn);
      box.appendChild(pager);
    }
  }


  /* ---- the live check -------------------------------------------------
     The snapshot is what makes this page fast and usable on conference
     wifi; it is not what makes it true. On load the page asks the catalog
     itself -- one request -- how many sessions it currently has, and says
     so if that disagrees with the copy being shown.

     Measured 2026-09-22 before building this: the catalog reflects any
     Origin back in Access-Control-Allow-Origin, its preflight names
     rfApiProfileId and rfWidgetId in Access-Control-Allow-Headers, and a
     real browser on another origin fetched all 1,582 sessions. So this
     needs no proxy and no server.

     Every failure path is silent and falls back to the snapshot, because
     the snapshot is already correct and a red banner about a CORS error
     helps nobody standing in a corridor. The only thing a failure costs
     is the live confirmation, and the age line still tells the truth.

     One request, not thirty-two: counting is cheap, and pulling the whole
     catalog on every page view would be rude to AWS and slow for the
     reader. The full pull happens only if they ask for it. */
  var live = { state: "idle", total: null, checkedAt: null };

  function liveHeaders() {
    var api = DATA.api;
    if (!api || !api.headers) return null;
    var h = { "Content-Type":
                "application/x-www-form-urlencoded; charset=UTF-8" };
    for (var k in api.headers) if (api.headers.hasOwnProperty(k))
      h[k] = api.headers[k];
    return h;
  }

  function liveFetch(extra) {
    var h = liveHeaders();
    if (!h) return Promise.reject(new Error("no api details in the store"));
    var body = new URLSearchParams({
      type: "session", browserTimezone: "America/Chicago",
      catalogDisplay: "list" });
    for (var k in (extra || {})) body.set(k, extra[k]);
    return fetch(DATA.api.url,
                 { method: "POST", headers: h, body: body.toString() })
      .then(function (r) {
        if (!r.ok) throw new Error("HTTP " + r.status);
        return r.json();
      });
  }

  function checkLive() {
    if (!DATA.api) return;
    live.state = "checking";
    liveFetch().then(function (d) {
      var total = parseInt(d.totalSearchItems, 10);
      if (isNaN(total)) throw new Error("no total in the response");
      live.total = total;
      live.checkedAt = Date.now();
      live.state = (total === DATA.sessions.length) ? "same" : "drift";
      renderFreshness();
    }).catch(function () {
      /* Silent on purpose. The snapshot stands, and the age line already
         tells the reader how old it is. */
      live.state = "unreachable";
      renderFreshness();
    });
  }

  function pullLive() {
    var btn = $("#live-pull");
    if (btn) { btn.disabled = true; btn.textContent = "Loading…"; }
    var all = [], PAGE = 50;

    function items(d) {
      if (d.items && d.items.length) return d.items;
      var sl = d.sectionList || [];
      return sl.length ? (sl[0].items || []) : [];
    }
    var expected = 0;

    /* Paced, because the catalog throttles a burst. Without the pause this
       stopped dead after two pages and handed back 100 sessions -- and the
       page then displayed those 100 as "live data", having thrown away a
       complete snapshot for a partial pull. That is the same failure the
       fetcher's shrink guard exists to prevent, so it gets the same
       answer: reconcile against the catalog's own total, and if the pull
       is short, keep the snapshot and say the pull failed. */
    function page(from) {
      return liveFetch(from ? { from: String(from) } : null)
        .then(function (d) {
          var got = items(d);
          all = all.concat(got);
          expected = parseInt(d.totalSearchItems, 10) || expected;
          if (got.length && all.length < expected)
            return new Promise(function (go) { setTimeout(go, 250); })
              .then(function () { return page(from + PAGE); });
          return all;
        });
    }
    page(0).then(function (raw) {
      if (!expected || raw.length < expected) {
        throw new Error("short pull: " + raw.length + " of " + expected);
      }
      DATA = reslim(raw, DATA);
      live.state = "live";
      live.checkedAt = Date.now();
      buildFilters();
      renderFreshness();
      render();
      if (!$("#plan").hidden) renderPlan();
      if (!$("#map").hidden) { fillMapDays(); renderMap(); }
    }).catch(function () {
      /* The snapshot is untouched and still on screen. */
      live.state = "pullfailed";
      renderFreshness();
    });
  }

  /* The browser's own copy of the slimming the fetcher does, so live data
     and stored data are exactly the same shape downstream. Facet tables are
     rebuilt from scratch rather than reusing the snapshot's, because an
     index into the wrong table renders as the wrong service name -- which
     would look like data rather than like a bug. */
  function reslim(raw, prev) {
    var FACETS = ["Type", "Level", "Role", "Services", "Topic",
                  "Area of Interest", "Industry"];
    var KEY = { "Type": "ty", "Level": "lv", "Role": "ro", "Services": "sv",
                "Topic": "tp", "Area of Interest": "ai", "Industry": "in" };
    var SINGLE = { "Type": 1, "Level": 1 };
    var tables = {}, venues = [], rooms = [];
    FACETS.forEach(function (f) { tables[f] = []; });

    function intern(list, v) {
      var i = list.indexOf(v);
      if (i === -1) { list.push(v); i = list.length - 1; }
      return i;
    }
    var out = raw.map(function (s) {
      var f = {};
      (s.attributevalues || []).forEach(function (av) {
        if (FACETS.indexOf(av.attribute) === -1 || !av.value) return;
        (f[av.attribute] = f[av.attribute] || []);
        if (f[av.attribute].indexOf(av.value) === -1)
          f[av.attribute].push(av.value);
      });
      var when = [];
      (s.times || []).forEach(function (t) {
        if (t.startTimeMin == null || t.endTimeMin == null) return;
        var b = t.startTimeMin | 0, e = t.endTimeMin | 0;
        var room = t.room || "";
        when.push({ d: t.date || "", b: b, e: e <= b ? null : e,
                    v: intern(venues, room.split("|")[0].trim()),
                    r: intern(rooms, room),
                    cap: /^\d+$/.test(String(t.capacity)) ? +t.capacity : null });
      });
      var rec = { c: s.code || "", t: (s.title || "").trim(),
                  a: (s.abstract || "").replace(/\s+/g, " ").trim(),
                  len: s.length ? (s.length | 0) : null, when: when };
      FACETS.forEach(function (name) {
        var idx = (f[name] || []).map(function (v) {
          return intern(tables[name], v); });
        rec[KEY[name]] = SINGLE[name] ? (idx.length ? idx[0] : null) : idx;
      });
      return rec;
    });

    var facets = {};
    FACETS.forEach(function (f) { facets[f] = tables[f]; });
    return { sessions: out, facets: facets, venues: venues, rooms: rooms,
             captured: prev.captured, captured_utc: prev.captured_utc,
             api: prev.api, live: true };
  }

  /* ---- how old is this, really ---------------------------------------
     Computed here rather than written in at build time, because the
     honest number is the one the reader is looking at now. A page built
     in September and opened in November has not got fresher, and a
     baked-in "captured 22 Sep" invites it to be read as if it had. */
  var AGING_DAYS = 10, STALE_DAYS = 21;

  function daysSince(iso) {
    if (!iso) return null;
    var then = new Date(iso);
    if (isNaN(then.getTime())) return null;
    return Math.floor((Date.now() - then.getTime()) / 86400000);
  }

  function renderFreshness() {
    var box = $("#fresh");
    var age = daysSince(DATA.captured_utc || DATA.captured);
    var when = DATA.captured || "an unrecorded date";
    box.textContent = "";

    /* Pulled live this session: the snapshot's age is no longer the
       interesting number, so it stops being the headline. */
    if (live.state === "live") {
      box.className = "fresh good";
      box.appendChild(el("b", null, "Showing live data"));
      box.appendChild(el("span", null,
        ", pulled from the AWS catalog a moment ago — "
        + DATA.sessions.length.toLocaleString() + " sessions. Seat "
        + "reservations still live in the "));
      addCatalogLink(box);
      return;
    }

    if (age === null) {
      box.className = "fresh stale";
      box.appendChild(el("span", null,
        "This copy of the catalog carries no capture date, so there is no "
        + "way to tell how old it is. Treat every time and room here as "
        + "unconfirmed and check the official catalog."));
      addCatalogLink(box);
      return;
    }

    var howLong = age === 0 ? "earlier today"
                : age === 1 ? "yesterday"
                : age + " days ago";
    var b = el("b", null, "Catalog checked " + howLong);
    box.appendChild(b);

    if (age >= STALE_DAYS) {
      box.className = "fresh stale";
      box.appendChild(el("span", null,
        " (" + when + "). That is old enough that sessions have probably "
        + "been added, moved or cancelled since. Confirm anything you are "
        + "relying on — every card links to its entry in the "));
      addCatalogLink(box);
    } else if (age >= AGING_DAYS) {
      box.className = "fresh aging";
      box.appendChild(el("span", null,
        " (" + when + "). Sessions move as the event gets closer, so check "
        + "anything you are relying on against the "));
      addCatalogLink(box);
    } else {
      box.className = "fresh good";
      box.appendChild(el("span", null,
        " (" + when + "), against " + DATA.sessions.length.toLocaleString()
        + " sessions. Seat reservations and last-minute changes still live "
        + "in the "));
      addCatalogLink(box);
    }
    appendLive(box);
  }

  /* What the one live request found, appended to whatever the age line
     already said. Drift is the case worth shouting about: it means the
     catalog has moved under this copy, and the reader can pull it now. */
  function appendLive(box) {
    if (live.state === "drift") {
      box.className = "fresh aging";
      box.appendChild(el("span", null,
        " AWS is currently listing " + live.total.toLocaleString()
        + " sessions against this copy's "
        + DATA.sessions.length.toLocaleString() + ". "));
      var btn = el("button", "livebtn", "Load the live catalog");
      btn.id = "live-pull";
      btn.addEventListener("click", pullLive);
      box.appendChild(btn);
    } else if (live.state === "same") {
      box.appendChild(el("span", "livenote",
        " Confirmed against AWS just now — same session count."));
    } else if (live.state === "pullfailed") {
      box.className = "fresh aging";
      box.appendChild(el("span", null,
        " The live catalog did not come back complete, so this is still "
        + "the stored copy rather than a half-loaded one. "));
      var again = el("button", "livebtn", "Try again");
      again.id = "live-pull";
      again.addEventListener("click", pullLive);
      box.appendChild(again);
    } else if (live.state === "unreachable") {
      box.appendChild(el("span", "livenote",
        " (Could not reach AWS to confirm just now; showing the stored "
        + "copy.)"));
    }
  }

  function addCatalogLink(box) {
    var a = el("a", null, "official catalog");
    a.href = CATALOG_URL;
    a.target = "_blank";
    a.rel = "noopener";
    box.appendChild(a);
    box.appendChild(document.createTextNode("."));
  }

  /* The whole cost table, visible. A number a reader cannot inspect is a
     number they have to take on faith, and this one changes their day. */
  function renderMatrix() {
    var host = $("#matrix");
    if (!host) return;
    var names = Object.keys(CFG.travel.matrix).sort();
    var t = el("table", "mx");
    var head = el("tr");
    head.appendChild(el("th", null, ""));
    names.forEach(function (n) { head.appendChild(el("th", null, n)); });
    t.appendChild(head);
    names.forEach(function (a) {
      var tr = el("tr");
      tr.appendChild(el("th", null, a));
      names.forEach(function (b) {
        var td = el("td");
        if (a === b) {
          td.textContent = tune.overhead + " min";
          td.className = "self";
        } else {
          var m = CFG.travel.matrix[a][b].m;
          td.appendChild(el("span", "mn", needFor(a, b) + " min"));
          td.appendChild(el("span", "md", km(m)));
        }
        tr.appendChild(td);
      });
      t.appendChild(tr);
    });
    host.textContent = "";
    host.appendChild(t);
  }


  /* ---- the map -------------------------------------------------------
     Drawn from the venues' real coordinates, to scale, with a bar showing
     what the scale is. It is rotated a quarter turn so the Strip runs
     left to right instead of producing a column 3.4 times taller than it
     is wide -- north is marked, because a map that silently reorients the
     world is worse than no map.

     No Google Maps embed, deliberately. A traffic layer here would be
     showing CAR congestion on Las Vegas Boulevard, which is not how
     anyone moves between these venues: it is walking, the conference
     shuttle and the monorail. It would look authoritative and mean
     nothing. Each hop instead links out to Google Maps for a real routed
     walking time, which costs no API key and opens the app already on
     the reader's phone. */
  /* ---- the map -------------------------------------------------------
     Drawn from real OpenStreetMap geometry -- building footprints and the
     actual street grid -- baked in at build time. The version this
     replaces was five circles on an empty background, which had the
     positions right and nothing else. Reported as: "what is this map? It
     doesn't make any sense ... at least I need to see the buildings, and
     the roads ... are we at the north side of the map or south?"

     NORTH IS UP, because that is what every map a person has ever used
     does, and the previous one's quarter turn was the reason that
     question had to be asked at all. The Strip runs NNE to SSW, so the
     result is tall and narrow -- which is the actual shape of the place,
     and sizing is driven off height so it fits a phone and a laptop
     without ever being cropped.

     No embed, deliberately. No API key, nothing third-party running in
     the reader's browser, and it still draws with the wifi down -- which
     is exactly when somebody in a packed hall needs to know which way the
     Venetian is. */
  var GEO = null, geoState = "idle", mapProj = null;

  /* Equirectangular, which is exact enough across two kilometres and keeps
     north pointing at the top of the screen. Metres, so the scale bar is
     arithmetic rather than a guess. */
  function projector(bbox) {
    var south = bbox[0], west = bbox[1], north = bbox[2], east = bbox[3];
    var mLat = 110540.0;
    var mLon = 111320.0 * Math.cos((south + north) / 2 * Math.PI / 180);
    var w = (east - west) * mLon, h = (north - south) * mLat;
    return {
      w: w, h: h,
      x: function (lon) { return (lon - west) * mLon; },
      y: function (lat) { return (north - lat) * mLat; }
    };
  }

  function svgEl(tag, attrs) {
    var n = document.createElementNS("http://www.w3.org/2000/svg", tag);
    for (var k in attrs) if (attrs.hasOwnProperty(k))
      n.setAttribute(k, attrs[k]);
    return n;
  }

  function mapsLink(a, b) {
    var pa = CFG.travel.points[a], pb = CFG.travel.points[b];
    return "https://www.google.com/maps/dir/?api=1"
         + "&origin=" + pa[0] + "," + pa[1]
         + "&destination=" + pb[0] + "," + pb[1]
         + "&travelmode=walking";
  }

  /* Road weights in METRES, so they scale with the map instead of needing
     a stroke-width that means something different at every size. */
  var ROAD_W = { motorway: 26, motorway_link: 14, trunk: 22, trunk_link: 12,
                 primary: 20, primary_link: 11, secondary: 15,
                 secondary_link: 9, tertiary: 12, residential: 8 };

  function loadGeo() {
    if (geoState === "loading" || geoState === "ready") return;
    geoState = "loading";
    fetch("/intelligence/vegas-map.json")
      .then(function (r) {
        if (!r.ok) throw new Error("HTTP " + r.status);
        return r.json();
      })
      .then(function (g) { GEO = g; geoState = "ready"; renderMap(); })
      .catch(function () { geoState = "failed"; renderMap(); });
  }

  function renderMap() {
    var host = $("#mapsvg");
    if (!host) return;

    if (geoState === "idle") { loadGeo(); }
    if (geoState === "loading" || geoState === "idle") {
      host.textContent = "";
      host.appendChild(el("p", "empty", "Drawing the map…"));
      return;
    }
    if (geoState === "failed" || !GEO) {
      host.textContent = "";
      host.appendChild(el("p", "empty",
        "The map geometry did not load. Everything else on this page still "
        + "works, and the distances below are unaffected."));
      renderHops(currentHops());
      return;
    }

    var P = projector(GEO.bbox);
    mapProj = P;
    var pad = padM;
    /* The geographic extent. The frame around it is derived later, in
       refit(), because the element has no height until the SVG is in the
       document -- measuring first gave an aspect near zero and a fit view
       27,474 metres wide, which is most of Nevada. */
    geoExtent = { x: -pad, y: -pad, w: P.w + pad * 2, h: P.h + pad * 2 };
    var fit = { x: geoExtent.x, y: geoExtent.y,
                w: geoExtent.w, h: geoExtent.h };
    var keep = (baseView && cam
                && Math.abs(baseView.w - fit.w) < 1) ? cam : null;
    baseView = fit;
    cam = keep || { x: fit.x, y: fit.y, w: fit.w, h: fit.h };
    var svg = svgEl("svg", {
      viewBox: (-pad) + " " + (-pad) + " " + (P.w + pad * 2) + " "
               + (P.h + pad * 2),
      preserveAspectRatio: "xMidYMid meet",
      class: "rimap", role: "img",
      "aria-label": "Map of the re:Invent venues on the Las Vegas Strip, "
        + "north at the top, showing building footprints and streets."
    });

    svg.appendChild(svgEl("rect", {
      x: -pad, y: -pad, width: P.w + pad * 2, height: P.h + pad * 2,
      class: "ground" }));

    function pathOf(pts, close) {
      var d = "";
      for (var i = 0; i < pts.length; i++)
        d += (i ? "L" : "M") + P.x(pts[i][1]).toFixed(1) + ","
             + P.y(pts[i][0]).toFixed(1);
      return d + (close ? "Z" : "");
    }

    /* Roads twice: a dark casing, then a lighter fill on top. That is how
       a street reads as a street rather than as a line. */
    var casing = svgEl("g", { class: "roadcase" });
    var fill = svgEl("g", { class: "roadfill" });
    GEO.roads.forEach(function (r) {
      var w = ROAD_W[r.c] || 8;
      var d = pathOf(r.p, false);
      casing.appendChild(svgEl("path", { d: d, "stroke-width": w + 6 }));
      fill.appendChild(svgEl("path", { d: d, "stroke-width": w }));
    });
    svg.appendChild(casing);
    svg.appendChild(fill);

    /* Buildings. Everything in muted grey for context; the five venues in
       the accent, because those are the only ones anyone is walking to. */
    var others = svgEl("g", { class: "bldg" });
    var ours = svgEl("g", { class: "bldg venue" });
    GEO.buildings.forEach(function (b) {
      var node = svgEl("path", { d: pathOf(b.p, true) });
      if (b.n) node.appendChild(svgEl("title", {})).textContent = b.n;
      (b.v ? ours : others).appendChild(node);
    });
    svg.appendChild(others);
    svg.appendChild(ours);

    /* The route for the chosen day, over the top of the streets. */
    var hops = currentHops();
    var routeG = svgEl("g", { class: "route" });
    hops.forEach(function (h, i) {
      var a = CFG.travel.points[h.from], b = CFG.travel.points[h.to];
      if (!a || !b || h.from === h.to) return;
      routeG.appendChild(svgEl("line", {
        x1: P.x(a[1]), y1: P.y(a[0]), x2: P.x(b[1]), y2: P.y(b[0]),
        class: "hop " + h.verdict }));
      var mx = (P.x(a[1]) + P.x(b[1])) / 2;
      var my = (P.y(a[0]) + P.y(b[0])) / 2;
      var lab = svgEl("text", { x: mx, y: my - 22,
                                class: "hoplab " + h.verdict,
                                "text-anchor": "middle" });
      lab.textContent = (i + 1) + ". " + h.gapText;
      routeG.appendChild(lab);
    });
    svg.appendChild(routeG);

    /* Venue pins, sized by how many of the filtered sessions are there.
       Tapping one filters the catalogue to that property. */
    var heat = {}, total = 0;
    Object.keys(CFG.travel.matrix).forEach(function (n) { heat[n] = 0; });
    filtered().forEach(function (sn) {
      var seen = {};
      sn.when.forEach(function (w) {
        var v = venueName(w);
        if (state.day && w.d !== state.day) return;
        if (seen[v]) return;
        seen[v] = 1;
        if (heat[v] === undefined) heat[v] = 0;
        heat[v] += 1; total += 1;
      });
    });
    var peak = Math.max.apply(null, Object.keys(heat).map(
      function (n) { return heat[n]; }).concat([1]));
    var nEl = $("#map-n");
    if (nEl) nEl.textContent = total.toLocaleString();

    var pins = svgEl("g", { class: "pins" });
    Object.keys(CFG.travel.points).forEach(function (name) {
      var p = CFG.travel.points[name];
      var cx = P.x(p[1]), cy = P.y(p[0]);
      var r = 34 + Math.round(Math.sqrt(heat[name] / peak || 0) * 56);
      var g = svgEl("g", { class: "pin" + (state.venue === name
                                           ? " on" : "") });
      g.appendChild(svgEl("circle", { cx: cx, cy: cy, r: r,
                                      class: "halo" }));
      g.appendChild(svgEl("circle", { cx: cx, cy: cy, r: 13,
                                      class: "dot" }));
      var num = svgEl("text", { x: cx, y: cy + r + 46, class: "vnum",
                                "text-anchor": "middle" });
      num.textContent = heat[name];
      var nm = svgEl("text", { x: cx, y: cy + r + 86, class: "vname",
                               "text-anchor": "middle" });
      nm.textContent = name;
      g.appendChild(num);
      g.appendChild(nm);
      g.addEventListener("click", function () {
        var turningOn = state.venue !== name;
        state.venue = turningOn ? name : "";
        shown = PAGE_SIZE;
        buildFilters();
        renderChips(); renderBrowse(); renderMap();
        if (turningOn) zoomToVenue(name);
      });
      var t = svgEl("title", {});
      t.textContent = name + " — " + heat[name] + " session(s) matching"
                      + " your filters. Tap to show only these.";
      g.appendChild(t);
      pins.appendChild(g);
    });
    svg.appendChild(pins);

    /* Compass. The question was literally "are we at the north side of the
       map or south", so this is not decoration. */
    var cx = P.w - 80, cy = 80;
    var comp = svgEl("g", { class: "compass" });
    comp.appendChild(svgEl("circle", { cx: cx, cy: cy, r: 54,
                                       class: "compdisc" }));
    comp.appendChild(svgEl("path", {
      d: "M" + cx + "," + (cy - 40) + "L" + (cx + 15) + "," + (cy + 12)
         + "L" + cx + "," + (cy + 2) + "L" + (cx - 15) + "," + (cy + 12) + "Z",
      class: "needle" }));
    var nlab = svgEl("text", { x: cx, y: cy + 40, class: "complab",
                               "text-anchor": "middle" });
    nlab.textContent = "N";
    comp.appendChild(nlab);
    svg.appendChild(comp);

    /* Scale bar, in metres, because the viewBox is already in metres. */
    var barM = 500, bx = 40, by = P.h - 40;
    var scale = svgEl("g", { class: "scale" });
    scale.appendChild(svgEl("line", { x1: bx, y1: by, x2: bx + barM, y2: by,
                                      class: "scalebar" }));
    scale.appendChild(svgEl("line", { x1: bx, y1: by - 10, x2: bx,
                                      y2: by + 10, class: "scalebar" }));
    scale.appendChild(svgEl("line", { x1: bx + barM, y1: by - 10,
                                      x2: bx + barM, y2: by + 10,
                                      class: "scalebar" }));
    var st = svgEl("text", { x: bx + barM / 2, y: by - 20,
                             class: "scaletxt", "text-anchor": "middle" });
    st.textContent = "500 m";
    scale.appendChild(st);
    svg.appendChild(scale);

    var attr = svgEl("text", { x: 10, y: P.h + 18, class: "attrib" });
    attr.textContent = GEO.attribution;
    svg.appendChild(attr);

    host.textContent = "";
    host.appendChild(svg);
    mapSvg = svg;
    refit(true);
    wireMapGestures(svg);
    wireMapButtons();
    renderHops(hops);
  }


  /* ---- pan and zoom ---------------------------------------------------
     Asked for: "can it have some sort of zoom option or expand option ...
     somehow it's kind of very plain".

     The viewBox is the camera. Everything is already drawn in metres, so
     zooming is arithmetic on four numbers and nothing has to be redrawn
     -- which is why this stays smooth on a phone with 1,000 paths on
     screen.

     Labels are the exception. Text in an SVG scales with the viewBox, so
     at 4x a room name would be four times the size of the screen. They
     are scaled inversely by --k so they hold a constant size however far
     in you are, which is what every real map does. */
  /* Named cam, not view: there is already a view(which) function for
     the tab switcher, and `var view` overwrote it -- the whole map
     died with "view is not a function". */
  var baseView = null, cam = null, mapSvg = null, geoExtent = null;
  var MIN_SPAN_M = 180;          // about one hotel across
  var padM = 30;

  function applyView() {
    if (!mapSvg || !cam) return;
    mapSvg.setAttribute("viewBox", cam.x.toFixed(1) + " " + cam.y.toFixed(1)
                        + " " + cam.w.toFixed(1) + " " + cam.h.toFixed(1));
    /* Labels were scaled by --k, the zoom ratio, which held them at a
       constant size but at the WRONG one: tuned against a 2,088px
       screenshot, they came out 6px on a 449px-wide desktop element and
       4.7px on a phone. Unreadable.

       --upx is user units per CSS pixel, measured from the element that
       is actually on screen. font-size: calc(13px * var(--upx)) is then
       exactly 13 CSS pixels at any zoom on any device, rather than
       whatever a ratio happens to produce. */
    var box = mapSvg.getBoundingClientRect();
    if (box.width && box.height) {
      // Match the camera to the element's shape, about its own centre, so
      // "meet" has nothing to letterbox.
      var want = box.height / box.width;
      if (Math.abs(cam.h / cam.w - want) > 0.001) {
        var midY = cam.y + cam.h / 2;
        cam.h = cam.w * want;
        cam.y = midY - cam.h / 2;
      }
      mapSvg.style.setProperty("--upx", (cam.w / box.width).toFixed(4));
    }
    mapSvg.style.setProperty("--k", (cam.w / baseView.w).toFixed(4));
    var fit = Math.abs(cam.w - baseView.w) < 1;
    var btn = $("#z-fit");
    if (btn) btn.disabled = fit;
  }

  /* Frame the whole campus inside a box shaped like the element, so the
     picture fills the space without distorting and without dead bands. */
  function refit(keepZoom) {
    if (!mapSvg || !geoExtent) return;
    var box = mapSvg.getBoundingClientRect();
    if (!box.width || !box.height) return;
    var aspect = box.height / box.width;
    var fw = geoExtent.w, fh = geoExtent.w * aspect;
    if (fh < geoExtent.h) { fh = geoExtent.h; fw = geoExtent.h / aspect; }
    var next = { x: geoExtent.x - (fw - geoExtent.w) / 2,
                 y: geoExtent.y - (fh - geoExtent.h) / 2, w: fw, h: fh };
    var zoomed = keepZoom && baseView && cam
                 && Math.abs(cam.w - baseView.w) > 1;
    var ratio = zoomed ? cam.w / baseView.w : 1;
    var midX = zoomed ? cam.x + cam.w / 2 : next.x + next.w / 2;
    var midY = zoomed ? cam.y + cam.h / 2 : next.y + next.h / 2;
    baseView = next;
    var w = next.w * ratio, h = next.h * ratio;
    cam = clampView({ x: midX - w / 2, y: midY - h / 2, w: w, h: h });
    applyView();
  }

  function clampView(v) {
    if (!baseView) return v;
    var maxW = baseView.w, maxH = baseView.h;
    if (v.w > maxW) { var f = maxW / v.w; v.w = maxW; v.h *= f; }
    if (v.w < MIN_SPAN_M) {
      var g = MIN_SPAN_M / v.w; v.w = MIN_SPAN_M; v.h *= g;
    }
    // Keep at least a corner of the map on screen rather than letting it
    // be dragged into empty space and lost.
    var slackX = v.w * 0.5, slackY = v.h * 0.5;
    v.x = Math.max(baseView.x - slackX,
                   Math.min(v.x, baseView.x + maxW - v.w + slackX));
    v.y = Math.max(baseView.y - slackY,
                   Math.min(v.y, baseView.y + maxH - v.h + slackY));
    return v;
  }

  function zoomAt(factor, clientX, clientY) {
    if (!mapSvg || !cam) return;
    var r = mapSvg.getBoundingClientRect();
    // Where the pointer is, in map coordinates -- so the thing under the
    // finger stays under the finger.
    var fx = (clientX - r.left) / r.width;
    var fy = (clientY - r.top) / r.height;
    var mx = cam.x + fx * cam.w, my = cam.y + fy * cam.h;
    var nw = cam.w / factor, nh = cam.h / factor;
    cam = clampView({ x: mx - fx * nw, y: my - fy * nh, w: nw, h: nh });
    applyView();
  }

  function zoomToVenue(name) {
    if (!baseView) return;
    var p = CFG.travel.points[name];
    if (!p || !mapProj) return;
    var span = 520;
    var cx = mapProj.x(p[1]), cy = mapProj.y(p[0]);
    var h = span * (baseView.h / baseView.w);
    cam = clampView({ x: cx - span / 2, y: cy - h / 2, w: span, h: h });
    applyView();
  }

  function wireMapGestures(svg) {
    var pointers = {}, lastMid = null, lastDist = 0, moved = false;

    svg.addEventListener("wheel", function (e) {
      e.preventDefault();
      zoomAt(e.deltaY < 0 ? 1.18 : 1 / 1.18, e.clientX, e.clientY);
    }, { passive: false });

    svg.addEventListener("pointerdown", function (e) {
      /* Capture is deliberately NOT taken here. Taking it on every press
         retargets the following click at the <svg>, so a tap on a venue
         pin never reached the pin's own handler -- the map panned fine
         and nothing was clickable. It is taken below, once a press has
         actually turned into a drag. */
      pointers[e.pointerId] = { x: e.clientX, y: e.clientY };
      moved = false;
      lastMid = null; lastDist = 0;
    });

    svg.addEventListener("pointermove", function (e) {
      if (!pointers[e.pointerId]) return;
      /* Read where this pointer WAS before overwriting it. Updating first
         made prev and current the same point, so every drag computed a
         delta of zero and the map never moved. */
      var was = pointers[e.pointerId];
      pointers[e.pointerId] = { x: e.clientX, y: e.clientY };
      var ids = Object.keys(pointers);
      var r = svg.getBoundingClientRect();

      if (ids.length === 1) {
        var prev = was;
        var dx = (e.clientX - prev.x) * (cam.w / r.width);
        var dy = (e.clientY - prev.y) * (cam.h / r.height);
        if (Math.abs(e.clientX - prev.x) + Math.abs(e.clientY - prev.y) > 2) {
          if (!moved) {
            moved = true;
            // Now it is a drag: keep the pointer even if it leaves the svg.
            try { svg.setPointerCapture(e.pointerId); } catch (err) {}
          }
        }
        cam = clampView({ x: cam.x - dx, y: cam.y - dy,
                           w: cam.w, h: cam.h });
        applyView();
      } else if (ids.length >= 2) {
        var a = pointers[ids[0]], b2 = pointers[ids[1]];
        var dist = Math.hypot(a.x - b2.x, a.y - b2.y);
        var mid = { x: (a.x + b2.x) / 2, y: (a.y + b2.y) / 2 };
        if (lastDist) {
          zoomAt(dist / lastDist, mid.x, mid.y);
          moved = true;
        }
        lastDist = dist;
        lastMid = null;
      }
    });

    function release(e) {
      delete pointers[e.pointerId];
      try { svg.releasePointerCapture(e.pointerId); } catch (err) {}
      if (!Object.keys(pointers).length) { lastMid = null; lastDist = 0; }
    }
    svg.addEventListener("pointerup", release);
    svg.addEventListener("pointercancel", release);
    svg.addEventListener("pointerleave", release);

    // A drag must not also count as a tap on whatever was underneath.
    svg.addEventListener("click", function (e) {
      if (moved) { e.stopPropagation(); e.preventDefault(); moved = false; }
    }, true);
  }

  function wireMapButtons() {
    function mid() {
      var r = mapSvg.getBoundingClientRect();
      return [r.left + r.width / 2, r.top + r.height / 2];
    }
    $("#z-in").onclick = function () {
      var m = mid(); zoomAt(1.5, m[0], m[1]); };
    $("#z-out").onclick = function () {
      var m = mid(); zoomAt(1 / 1.5, m[0], m[1]); };
    $("#z-fit").onclick = function () {
      cam = { x: baseView.x, y: baseView.y, w: baseView.w, h: baseView.h };
      applyView();
    };
    var box = $("#mapwrap"), full = $("#z-full");
    full.onclick = function () {
      if (document.fullscreenElement) {
        document.exitFullscreen();
      } else if (box.requestFullscreen) {
        box.requestFullscreen().catch(function () {});
      } else {
        // Safari on iOS has no element fullscreen; fall back to a class
        // that fills the viewport, which is the part people actually want.
        box.classList.toggle("faux-full");
        full.textContent = box.classList.contains("faux-full")
          ? "Close" : "Expand";
      }
    };
    document.addEventListener("fullscreenchange", function () {
      full.textContent = document.fullscreenElement ? "Close" : "Expand";
    });
  }

  /* The element's width is part of the type scale, so a resize or an
     orientation change has to recompute it. */
  window.addEventListener("resize", function () {
    if (mapSvg && cam) refit(true);
  });

  function currentHops() {
    var sel = $("#map-day");
    var day = sel ? sel.value : "";
    return day ? routeFor(day) : [];
  }

  /* The day's hops, reusing exactly the plan's own feasibility rule so the
     map and the plan can never disagree with each other. */
  function routeFor(day) {
    var rows = planRows().filter(function (r) {
      return r.d === day && r.w;
    });
    var out = [];
    for (var i = 1; i < rows.length; i++) {
      var a = rows[i - 1], b = rows[i];
      var from = venueName(a.w), to = venueName(b.w);
      if (a.w.e == null) {
        out.push({ from: from, to: to, verdict: "warn", a: a, b: b,
                   gapText: "end time not published" });
        continue;
      }
      var gap = b.w.b - a.w.e, need = needFor(from, to);
      var verdict = gap < 0 ? "bad" : gap < need ? "warn" : "ok";
      out.push({ from: from, to: to, verdict: verdict, a: a, b: b,
                 gap: gap, need: need,
                 gapText: gap < 0 ? "overlap" : gap + " min / needs " + need });
    }
    return out;
  }

  function renderHops(hops) {
    var host = $("#maphops");
    if (!host) return;
    host.textContent = "";
    if (!hops.length) return;
    hops.forEach(function (h, i) {
      var row = el("div", "hoprow " + h.verdict);
      row.appendChild(el("span", "hopn", String(i + 1)));
      var txt = el("span", "hopt");
      txt.textContent = h.from + " → " + h.to
        + (h.from === h.to ? " (same property)"
           : "  ·  " + km(metresBetween(h.from, h.to)) + "  ·  "
             + h.gapText);
      row.appendChild(txt);
      if (h.from !== h.to) {
        var a = el("a", "hoplink", "walking route ↗");
        a.href = mapsLink(h.from, h.to);
        a.target = "_blank"; a.rel = "noopener";
        a.title = "Open this hop in Google Maps for a live routed time";
        row.appendChild(a);
      }
      host.appendChild(row);
    });
  }

  /* The route is drawn from YOUR PLAN, so the day list only holds days
     you have starred something on. With an empty plan that left an
     enabled dropdown offering exactly one entry -- "no day selected" --
     and no hint as to why. Reported as "so why it shows no days
     selected", which is the right question to ask of a control that
     appears to work and does nothing.

     A control with nothing to offer should say so and be unusable, not
     sit there looking operable. */
  function fillMapDays() {
    var sel = $("#map-day");
    if (!sel) return;
    var have = {};
    planRows().forEach(function (r) { if (r.w) have[r.d] = 1; });
    var days = CFG.days.filter(function (d) { return have[d]; });
    var keep = sel.value;
    sel.textContent = "";

    if (!days.length) {
      sel.appendChild(new Option(
        plan.length ? "— nothing scheduled in your plan yet —"
                    : "— star sessions first —", ""));
      sel.disabled = true;
      sel.onchange = null;
      setMapHint(plan.length
        ? "The sessions in your plan have no published times yet, so there "
          + "is no route to draw."
        : "Star a few sessions in Browse and their route across the Strip "
          + "appears here, with the tight hops flagged.");
      return;
    }

    sel.disabled = false;
    sel.appendChild(new Option("— no day selected —", ""));
    days.forEach(function (d) {
      sel.appendChild(new Option(dayLabel(d), d));
    });
    sel.value = have[keep] ? keep : "";
    sel.onchange = function () { renderMap(); dayPrompt(days.length); };
    dayPrompt(days.length);
  }

  /* Cleared once a day is chosen: a prompt telling you to do the thing
     you have just done is noise. It was not being cleared, because only
     fillMapDays set it and the dropdown's own change never re-ran it. */
  function dayPrompt(n) {
    var sel = $("#map-day");
    if (sel && sel.value) { setMapHint(""); return; }
    setMapHint(n === 1
      ? "Pick the day above to draw the route."
      : "Pick one of your " + n + " days above to draw the route.");
  }

  function setMapHint(text) {
    var el_ = $("#mapday-hint");
    if (!el_) return;
    el_.textContent = text || "";
    el_.hidden = !text;
  }

  function laneName(id) {
    for (var i = 0; i < CFG.lanes.length; i++)
      if (CFG.lanes[i].id === id) return CFG.lanes[i].name;
    return id;
  }

  /* ---- the plan ------------------------------------------------------ */
  function inPlan(code) { return plan.indexOf(code) !== -1; }
  function toggle(code) {
    var i = plan.indexOf(code);
    if (i === -1) plan.push(code); else plan.splice(i, 1);
    save(PLAN_KEY, plan);
    syncStars(); renderPlan();
    if (!$("#map").hidden) { fillMapDays(); renderMap(); }
  }
  function syncStars() {
    $("#planN").textContent = plan.length;
    Array.prototype.forEach.call(
      document.querySelectorAll(".card"), function (c) {
        var on = inPlan(c.dataset.code), b = c.querySelector(".star");
        if (!b) return;
        b.textContent = on ? "★" : "☆";
        b.setAttribute("aria-pressed", on ? "true" : "false");
        b.title = on ? "Remove from my plan" : "Add to my plan";
      });
  }

  function planRows() {
    var by = {}, rows = [];
    DATA.sessions.forEach(function (s) { by[s.c] = s; });
    plan.forEach(function (code) {
      var s = by[code];
      if (!s) {
        /* The session is starred and is no longer in the catalog. Dropping
           it silently was the worst thing this page could do: the plan
           would simply be one session shorter than the person built, with
           nothing to say a talk they were counting on has gone. */
        rows.push({ gone: code, d: "zzzz" });
        return;
      }
      if (!s.when.length) { rows.push({ s: s, w: null, d: "zzz" }); return; }
      s.when.forEach(function (w) { rows.push({ s: s, w: w, d: w.d }); });
    });
    rows.sort(function (a, b) {
      if (a.d !== b.d) return a.d < b.d ? -1 : 1;
      if (!a.w || !b.w) return a.w ? -1 : 1;
      return a.w.b - b.w.b;
    });
    return rows;
  }

  function renderPlan() {
    var box = $("#planbody");
    box.textContent = "";
    var rows = planRows();
    if (!rows.length) {
      box.appendChild(el("p", "empty",
        "Nothing starred yet. Star a session in Browse and it lands here, "
        + "with the travel between them checked."));
      return;
    }

    var group = null, host = null, prev = null;
    rows.forEach(function (r) {
      if (r.d !== group) {
        group = r.d; prev = null;
        host = el("section", "daygroup");
        host.appendChild(el("h2", "dayhead",
          r.gone ? "No longer in the catalog"
                 : r.w ? dayLabel(r.d) : "Not yet scheduled"));
        box.appendChild(host);
      }
      if (r.gone) { host.appendChild(goneCard(r.gone)); prev = null; return; }
      if (prev && prev.w && r.w) host.appendChild(gapRow(prev, r));
      var c = card(r.s, r.w);
      var vr = verdictRow(r.s.c);
      if (vr) c.appendChild(vr);
      c.appendChild(noteBox(r.s.c));
      host.appendChild(c);
      prev = r;
    });
  }

  function goneCard(code) {
    var c = el("article", "card gone");
    c.dataset.code = code;
    var top = el("div", "top");
    top.appendChild(el("span", "code", code));
    top.appendChild(el("span", "tag", "withdrawn or renamed"));
    c.appendChild(top);
    c.appendChild(el("h3", null, "This session is no longer in the catalog"));
    var where = el("div", "where");
    where.appendChild(document.createTextNode(
      "You starred it, and the capture of " + (DATA.captured || "the catalog")
      + " does not contain it. AWS may have withdrawn, merged or renumbered "
      + "it. Check "));
    var a = el("a", null, code + " in the official catalog");
    a.href = CATALOG_URL + "?search=" + encodeURIComponent(code);
    a.target = "_blank"; a.rel = "noopener";
    where.appendChild(a);
    where.appendChild(document.createTextNode("."));
    c.appendChild(where);
    var drop = el("button", "star", "×");
    drop.title = "Remove it from my plan";
    drop.addEventListener("click", function () { toggle(code); });
    c.appendChild(drop);
    return c;
  }

  function gapRow(a, b) {
    var from = venueName(a.w), to = venueName(b.w);
    var need = needFor(from, to);
    var row = el("div", "gap"), msg;

    if (a.w.e == null) {
      /* No published end, so there is no gap to measure. The page says
         that rather than measuring from the start time and calling the
         result a gap -- which would under-warn on exactly the hop this
         feature exists to catch. */
      row.className = "gap warn";
      row.appendChild(el("span", "ic", "○"));
      row.appendChild(el("span", null,
        "AWS does not publish how long " + a.s.c + " runs, so the time "
        + "before " + b.s.c + " cannot be checked."
        + (from === to ? "" : " They are at different properties — "
           + from + " to " + to + " — so allow about " + need + " min.")));
      return row;
    }

    var gap = b.w.b - a.w.e;
    if (gap < 0) {
      row.className = "gap bad";
      row.appendChild(el("span", "ic", "●"));
      msg = "These overlap by " + (-gap) + " min. " +
        (from === to ? "Same property, but you cannot be in both."
                     : from + " and " + to + " at once is not possible.");
    } else if (gap < need) {
      row.className = "gap warn";
      row.appendChild(el("span", "ic", "●"));
      msg = gap + " min between them" +
        (from === to ? " inside " + from
                     : ", and they are " + km(metresBetween(from, to))
                       + " apart — " + from + " to " + to) +
        ". Allow about " + need + ". You would be late.";
    } else {
      row.className = "gap ok";
      row.appendChild(el("span", "ic", "○"));
      msg = gap + " min" +
        (from === to ? " to change rooms inside " + from
                     : " to cover the " + km(metresBetween(from, to))
                       + " from " + from + " to " + to) + ".";
    }
    row.appendChild(el("span", null, msg));
    return row;
  }


  /* ---- taking it with you --------------------------------------------
     Two exports, because a plan that only exists on this page is a plan
     nobody looks at on the day.

     TIMEZONE. Every event is emitted in UTC, which needs no VTIMEZONE
     block and cannot be misread by a client. The conversion is exact
     rather than assumed: all 1,555 scheduled slots in the catalog were
     checked against their own utcEndTime, and every one came back at
     UTC = local + 8h. That is Pacific Standard Time, and re:Invent 2026
     sits wholly after the November DST change, so there is no transition
     inside the event for a fixed offset to get wrong. */
  var VEGAS_OFFSET_H = 8;

  function icsStamp(day, minutes) {
    var d = new Date(day + "T00:00:00Z");
    d.setUTCMinutes(d.getUTCMinutes() + minutes + VEGAS_OFFSET_H * 60);
    return d.toISOString().replace(/[-:]/g, "").replace(/\.\d{3}/, "");
  }

  /* iCalendar escaping, then folding at 75 octets with CRLF + space.
     Clients genuinely do break on an unfolded 300-character DESCRIPTION,
     and the failure looks like a corrupt file rather than a long line. */
  function icsText(v) {
    return String(v || "").replace(/\\/g, "\\\\").replace(/;/g, "\\;")
      .replace(/,/g, "\\,").replace(/\r?\n/g, "\\n");
  }

  /* RFC 5545 folds at 75 OCTETS, not characters, and a continuation line
     spends one of them on its leading space. Counting characters passed a
     em dash and a middot straight through: 15 lines went out over the
     limit while still looking 74 long. Split on a code point boundary too,
     or a folded line can end mid-character and the client sees mojibake. */
  function icsFold(line) {
    var enc = new TextEncoder();
    if (enc.encode(line).length <= 75) return line;
    var out = [], cur = "", curBytes = 0;
    for (var i = 0; i < line.length; ) {
      var cp = String.fromCodePoint(line.codePointAt(i));
      i += cp.length;
      var b = enc.encode(cp).length;
      var cap = out.length ? 74 : 75;      // continuations carry a space
      if (curBytes + b > cap) {
        out.push(cur);
        cur = ""; curBytes = 0;
      }
      cur += cp; curBytes += b;
    }
    if (cur) out.push(cur);
    return out.map(function (seg, i) {
      return (i ? " " : "") + seg;
    }).join("\r\n");
  }

  function buildICS() {
    var now = new Date().toISOString().replace(/[-:]/g, "")
                .replace(/\.\d{3}/, "");
    var lines = ["BEGIN:VCALENDAR", "VERSION:2.0",
                 "PRODID:-//jayanthkatta.com//re:Invent 2026 planner//EN",
                 "CALSCALE:GREGORIAN", "METHOD:PUBLISH",
                 "X-WR-CALNAME:AWS re:Invent 2026"];
    var count = 0;
    planRows().forEach(function (r) {
      if (r.gone || !r.w) return;
      var s = r.s, w = r.w;
      // The eleven sessions AWS publishes with no duration get an hour,
      // and the description says so rather than pretending otherwise.
      var unknownEnd = (w.e == null);
      var end = unknownEnd ? w.b + 60 : w.e;
      var desc = [];
      if (unknownEnd)
        desc.push("AWS has not published a length for this session; one "
                + "hour is assumed here.");
      if (speakerNames(s).length)
        desc.push("Speakers: " + speakerNames(s).join("; "));
      if (svcNames(s).length)
        desc.push("Services: " + svcNames(s).join(", "));
      if (w.cap) desc.push("Room capacity: " + w.cap);
      desc.push("Confirm in the official catalog: "
              + CATALOG_URL + "?search=" + encodeURIComponent(s.c));
      if (s.a) desc.push("", s.a);

      lines.push("BEGIN:VEVENT");
      lines.push(icsFold("UID:" + s.c + "-" + w.d
                         + "@reinvent2026.jayanthkatta.com"));
      lines.push("DTSTAMP:" + now);
      lines.push("DTSTART:" + icsStamp(w.d, w.b));
      lines.push("DTEND:" + icsStamp(w.d, end));
      lines.push(icsFold("SUMMARY:" + icsText(s.c + " — " + s.t)));
      lines.push(icsFold("LOCATION:" + icsText(roomName(w))));
      lines.push(icsFold("DESCRIPTION:" + icsText(desc.join("\n"))));
      lines.push(icsFold("URL:" + CATALOG_URL + "?search="
                         + encodeURIComponent(s.c)));
      lines.push("END:VEVENT");
      count += 1;
    });
    lines.push("END:VCALENDAR");
    return { text: lines.join("\r\n"), count: count };
  }

  function download(name, text, mime) {
    var blob = new Blob([text], { type: mime + ";charset=utf-8" });
    var url = URL.createObjectURL(blob);
    var a = document.createElement("a");
    a.href = url; a.download = name;
    document.body.appendChild(a); a.click();
    document.body.removeChild(a);
    setTimeout(function () { URL.revokeObjectURL(url); }, 1000);
  }

  /* ---- notes, and the trip report they become ------------------------
     You come back from five days having sat in thirty sessions with
     nothing written down. A note per session, kept in this browser, and
     an export that is already the shape of something you would send to
     the team. */
  var NOTE_KEY = "ri2026.notes";
  var notes = load(NOTE_KEY, {}) || {};

  function noteFor(code) { return notes[code] || ""; }

  function setNote(code, text) {
    if (text) notes[code] = text; else delete notes[code];
    save(NOTE_KEY, notes);
  }

  function noteBox(code) {
    var wrap = el("div", "notewrap");
    var ta = document.createElement("textarea");
    ta.className = "note";
    ta.rows = 2;
    ta.placeholder = "What did you take away? (kept on this device)";
    ta.value = noteFor(code);
    ta.addEventListener("input", function () { setNote(code, ta.value); });
    wrap.appendChild(ta);
    return wrap;
  }

  function buildMarkdown() {
    var out = ["# AWS re:Invent 2026 — session notes", ""];
    var seen = 0, group = null;
    planRows().forEach(function (r) {
      if (r.gone) {
        out.push("- ~~" + r.gone + "~~ (no longer in the catalog)");
        return;
      }
      if (r.d !== group) {
        group = r.d;
        out.push("", "## " + (r.w ? dayLabel(r.d) : "Not yet scheduled"), "");
      }
      var s = r.s, w = r.w;
      var when = w ? hhmm(w.b) + (w.e == null ? "" : "–" + hhmm(w.e)) : "";
      out.push("### " + s.c + " — " + s.t);
      var meta = [];
      if (when) meta.push(when);
      if (w) meta.push(roomName(w));
      if (typeName(s)) meta.push(typeName(s));
      if (levelName(s)) meta.push(levelName(s));
      out.push("*" + meta.join(" · ") + "*");
      if (speakerNames(s).length)
        out.push("", "Speakers: " + speakerNames(s).join("; "));
      var note = noteFor(s.c);
      out.push("", note ? note : "_No notes._");
      out.push("", "[Official catalog entry](" + CATALOG_URL + "?search="
               + encodeURIComponent(s.c) + ")", "");
      seen += 1;
    });
    out.push("", "---", "",
             "Generated from jayanthkatta.com/reinvent-2026/ · "
             + seen + " session(s) · catalog captured "
             + (DATA.captured || "unknown"));
    return out.join("\n");
  }


  /* ---- verifying the plan against AWS --------------------------------
     The load-time live check compares session COUNTS, which catches an
     addition or a cancellation and misses a move. Six sessions were
     re-roomed in two hours on 2026-09-22 without the count changing at
     all, so the count check would have said "same" while a plan quietly
     pointed at the wrong building.

     This closes that, on the only sessions it matters for: the ones you
     starred. Measured first -- the API honours search=<code> and returns
     exactly one row -- so a plan costs one small request per session
     rather than a full catalog pull. Paced, because the catalog throttles
     a burst; that was found the hard way when a burst returned 100
     sessions and the page displayed them as live data. */
  var verified = {};      // code -> {state, was, now}

  function slotSig(d, b, e, room) {
    return [d, b, e == null ? "?" : e, room].join("|");
  }

  function verifyPlan() {
    var btn = $("#verify");
    var codes = plan.slice();
    if (!codes.length || !DATA.api) return;
    var done = 0;

    function setLabel(t) { if (btn) btn.textContent = t; }
    if (btn) btn.disabled = true;

    function step(i) {
      if (i >= codes.length) {
        setLabel("Re-check against AWS");
        if (btn) btn.disabled = false;
        renderPlan();
        return;
      }
      var code = codes[i];
      setLabel("Checking " + (i + 1) + " of " + codes.length + "…");
      liveFetch({ search: code }).then(function (d) {
        var items = d.items && d.items.length ? d.items
                  : ((d.sectionList || [{}])[0].items || []);
        var hit = null;
        items.forEach(function (it) { if (it.code === code) hit = it; });
        var mine = null;
        DATA.sessions.forEach(function (x) { if (x.c === code) mine = x; });

        if (!hit) {
          verified[code] = { state: "gone" };
        } else {
          var t = (hit.times || [])[0];
          if (!t || t.startTimeMin == null) {
            verified[code] = { state: "unscheduled" };
          } else {
            var liveEnd = (t.endTimeMin != null
                           && t.endTimeMin > t.startTimeMin)
                        ? (t.endTimeMin | 0) : null;
            var liveSig = slotSig(t.date, t.startTimeMin | 0, liveEnd,
                                  t.room || "");
            var w = mine && mine.when.length ? mine.when[0] : null;
            var mineSig = w ? slotSig(w.d, w.b, w.e, roomName(w)) : "none";
            verified[code] = (liveSig === mineSig)
              ? { state: "ok" }
              : { state: "changed",
                  now: { d: t.date, b: t.startTimeMin | 0, e: liveEnd,
                         room: t.room || "" } };
          }
        }
        done += 1;
        setTimeout(function () { step(i + 1); }, 220);
      }).catch(function () {
        verified[code] = { state: "unchecked" };
        setTimeout(function () { step(i + 1); }, 220);
      });
    }
    step(0);
  }

  function verdictRow(code) {
    var v = verified[code];
    if (!v) return null;
    var row = el("div", "vrow");
    if (v.state === "ok") {
      row.className = "vrow ok";
      row.textContent = "✓ Confirmed against AWS just now.";
    } else if (v.state === "changed") {
      row.className = "vrow bad";
      row.textContent = "⚠ AWS now has this at "
        + hhmm(v.now.b) + (v.now.e == null ? "" : "–" + hhmm(v.now.e))
        + " on " + v.now.d + ", " + v.now.room
        + ". The card above is the stored copy.";
    } else if (v.state === "gone") {
      row.className = "vrow bad";
      row.textContent = "⚠ AWS no longer returns this session code.";
    } else if (v.state === "unscheduled") {
      row.className = "vrow warn";
      row.textContent = "AWS currently lists this with no time.";
    } else {
      row.className = "vrow";
      row.textContent = "Could not reach AWS to check this one.";
    }
    return row;
  }

  /* ---- what is on now, near me ---------------------------------------
     The catalog is least usable at exactly the moment you need it most:
     237 sessions start at 13:00. This answers the standing-in-a-corridor
     question -- what starts soon, here, and what can I still reach.

     Outside the event it has no "now" worth showing, so it says so and
     lets you preview a day and time rather than rendering an empty panel
     and looking broken. */
  var NOW_KEY = "ri2026.where";
  var nowState = load(NOW_KEY, null) || { at: "", day: "", time: 540 };
  var WINDOW_MIN = 90;

  function eventNow() {
    var d = new Date();
    var iso = d.getFullYear() + "-"
            + String(d.getMonth() + 1).padStart(2, "0") + "-"
            + String(d.getDate()).padStart(2, "0");
    if (CFG.days.indexOf(iso) === -1) return null;
    return { day: iso, min: d.getHours() * 60 + d.getMinutes() };
  }

  function renderNow() {
    var host = $("#nowbody");
    if (!host) return;
    host.textContent = "";

    var real = eventNow();
    var live_ = real || { day: nowState.day || CFG.days[0],
                          min: nowState.time };
    var note = $("#nownote");
    if (note) {
      /* Three states, not two. "has not started" was being shown in
         December as well, which is a small lie on a page whose whole
         claim is that it does not tell them. */
      var last = CFG.days[CFG.days.length - 1];
      var today = new Date();
      var iso = today.getFullYear() + "-"
              + String(today.getMonth() + 1).padStart(2, "0") + "-"
              + String(today.getDate()).padStart(2, "0");
      note.textContent = real
        ? "Live: it is " + hhmm(live_.min) + " on " + dayLabel(live_.day) + "."
        : (iso > last
           ? "re:Invent 2026 has finished. You can still look back over any "
             + "day — pick one below."
           : "re:Invent has not started, so this is a preview — pick a "
             + "day and time. During the event it uses the real clock.");
      note.className = real ? "nownote live" : "nownote";
    }
    var picker = $("#nowpick");
    if (picker) picker.hidden = !!real;

    var here = nowState.at;
    var rows = [];
    DATA.sessions.forEach(function (sn) {
      sn.when.forEach(function (w) {
        if (w.d !== live_.day) return;
        var mins = w.b - live_.min;
        if (mins < -5 || mins > WINDOW_MIN) return;
        var v = venueName(w);
        var need = here ? needFor(here, v) : 0;
        rows.push({ s: sn, w: w, in: mins, venue: v,
                    reach: !here || mins >= need, need: need });
      });
    });
    rows.sort(function (a, b) {
      if (a.reach !== b.reach) return a.reach ? -1 : 1;
      return a.in - b.in;
    });

    var can = rows.filter(function (r) { return r.reach; });
    var cant = rows.filter(function (r) { return !r.reach; });

    var head = el("p", "count");
    head.innerHTML = "<b>" + can.length + "</b> session"
      + (can.length === 1 ? "" : "s") + " you can still get to in the next "
      + WINDOW_MIN + " minutes"
      + (here ? ", starting from " + here : "")
      + (cant.length ? "  ·  " + cant.length + " you could not reach in time"
                     : "");
    host.appendChild(head);

    if (!rows.length) {
      host.appendChild(el("p", "empty",
        "Nothing starts in the next " + WINDOW_MIN + " minutes on this day."));
      return;
    }

    function block(title, list, cls) {
      if (!list.length) return;
      var sec = el("section", "daygroup");
      sec.appendChild(el("h2", "dayhead", title));
      list.slice(0, 40).forEach(function (r) {
        var c = card(r.s, r.w);
        if (cls) c.classList.add(cls);
        var when = el("div", "where");
        when.textContent = (r.in <= 0 ? "started " + (-r.in) + " min ago"
                                      : "starts in " + r.in + " min")
          + (here && r.venue !== here
             ? "  ·  " + km(metresBetween(here, r.venue)) + " away, allow "
               + r.need + " min"
             : here ? "  ·  you are here" : "");
        c.insertBefore(when, c.querySelector(".more") || null);
        sec.appendChild(c);
      });
      host.appendChild(sec);
    }
    block("Reachable", can, null);
    block("Too far to make it", cant, "unreachable");
  }

  function fillNowControls() {
    var at = $("#now-at"), day = $("#now-day"), time = $("#now-time");
    if (!at) return;
    if (!at.options.length) {
      at.appendChild(new Option("— pick where you are —", ""));
      Object.keys(CFG.travel.matrix).sort().forEach(function (v) {
        at.appendChild(new Option(v, v));
      });
      CFG.days.forEach(function (d) {
        day.appendChild(new Option(dayLabel(d), d));
      });
    }
    at.value = nowState.at || "";
    day.value = nowState.day || CFG.days[0];
    time.value = hhmm(nowState.time || 540);
    at.onchange = function () {
      nowState.at = at.value; save(NOW_KEY, nowState); renderNow();
    };
    day.onchange = function () {
      nowState.day = day.value; save(NOW_KEY, nowState); renderNow();
    };
    time.onchange = function () {
      var p = /^(\d{1,2}):(\d{2})$/.exec(time.value);
      if (p) {
        nowState.time = (+p[1]) * 60 + (+p[2]);
        save(NOW_KEY, nowState); renderNow();
      }
    };
  }


  /* ---- team coverage --------------------------------------------------
     The point of sending six people to 1,582 sessions is that they do not
     all sit in the same room. Nothing in the official catalog knows a team
     exists, so this merges plans: everyone shares their plan link, they go
     in here, and it says who is doubled up and which hours nobody is
     covering.

     No backend and no accounts. A plan already travels in its own URL, so
     the merge is pasting text. Nothing is uploaded anywhere. */
  var TEAM_KEY = "ri2026.team";

  function parseTeam(text) {
    var people = [];
    (text || "").split(/\r?\n/).forEach(function (line) {
      line = line.trim();
      if (!line) return;
      var name = "", rest = line;
      var colon = line.indexOf(":");
      // "Asha: <link>" -- but not the colon in "https://"
      if (colon > 0 && !/^https?$/i.test(line.slice(0, colon))) {
        name = line.slice(0, colon).trim();
        rest = line.slice(colon + 1).trim();
      }
      var m = /[#&]plan=([^&\s]*)/.exec(rest);
      var codes = (m ? decodeURIComponent(m[1]) : rest)
        .split(/[,\s]+/).map(function (c) { return c.trim().toUpperCase(); })
        .filter(Boolean);
      if (!codes.length) return;
      people.push({ name: name || ("Person " + (people.length + 1)),
                    codes: codes });
    });
    return people;
  }

  function renderTeam() {
    var host = $("#teambody");
    if (!host) return;
    host.textContent = "";

    var people = parseTeam($("#teamin") ? $("#teamin").value : "");
    if (plan.length) people.unshift({ name: "You", codes: plan.slice() });
    if (!people.length) {
      host.appendChild(el("p", "empty",
        "Paste one plan link per line. Everyone gets their own link from "
        + "My plan → Copy a link to this plan."));
      return;
    }

    var by = {};
    DATA.sessions.forEach(function (x) { by[x.c] = x; });

    // who is going to what
    var who = {}, unknown = [];
    people.forEach(function (p) {
      p.codes.forEach(function (c) {
        if (!by[c]) { if (unknown.indexOf(c) === -1) unknown.push(c); return; }
        (who[c] = who[c] || []).push(p.name);
      });
    });

    var codes = Object.keys(who);
    var head = el("p", "count");
    head.innerHTML = "<b>" + people.length + "</b> "
      + (people.length === 1 ? "person" : "people") + " · <b>"
      + codes.length + "</b> distinct session"
      + (codes.length === 1 ? "" : "s") + " covered";
    host.appendChild(head);

    // doubled up
    var dup = codes.filter(function (c) { return who[c].length > 1; });
    var sec = el("section", "teamsec");
    sec.appendChild(el("h3", null, dup.length
      ? dup.length + " session(s) more than one of you is in"
      : "Nobody is doubled up"));
    if (dup.length) {
      sec.appendChild(el("p", "teamhint",
        "Worth a look: two people in one room is one room nobody else is "
        + "in. Sometimes that is deliberate."));
      dup.forEach(function (c) {
        var r = el("div", "teamrow dup");
        r.appendChild(el("span", "tcode", c));
        r.appendChild(el("span", "ttitle", by[c].t));
        r.appendChild(el("span", "twho", who[c].join(", ")));
        sec.appendChild(r);
      });
    }
    host.appendChild(sec);

    // hours nobody is in anything
    var gaps = el("section", "teamsec");
    gaps.appendChild(el("h3", null, "Hours nobody has anything booked"));
    var busy = {};
    codes.forEach(function (c) {
      (by[c].when || []).forEach(function (w) {
        var end = w.e == null ? w.b + 60 : w.e;
        for (var m = w.b; m < end; m += 30)
          busy[w.d + "|" + (Math.floor(m / 30) * 30)] = true;
      });
    });
    var any = false;
    CFG.days.forEach(function (d) {
      var free = [];
      for (var m = 8 * 60; m < 18 * 60; m += 30)
        if (!busy[d + "|" + m]) free.push(m);
      if (!free.length) return;
      // collapse consecutive half-hours into ranges
      var runs = [], start = null, prev = null;
      free.forEach(function (m) {
        if (start === null) { start = m; prev = m; return; }
        if (m === prev + 30) { prev = m; return; }
        runs.push([start, prev + 30]); start = m; prev = m;
      });
      if (start !== null) runs.push([start, prev + 30]);
      var r = el("div", "teamrow");
      r.appendChild(el("span", "tday", dayLabel(d)));
      r.appendChild(el("span", "ttitle", runs.map(function (x) {
        return hhmm(x[0]) + "–" + hhmm(x[1]); }).join(",  ")));
      gaps.appendChild(r);
      any = true;
    });
    if (!any) gaps.appendChild(el("p", "teamhint",
      "Every half-hour between 08:00 and 18:00 has somebody in something."));
    host.appendChild(gaps);

    // per person
    var per = el("section", "teamsec");
    per.appendChild(el("h3", null, "Who is doing what"));
    people.forEach(function (p) {
      var r = el("div", "teamrow");
      r.appendChild(el("span", "tday", p.name));
      var known = p.codes.filter(function (c) { return by[c]; });
      r.appendChild(el("span", "ttitle",
        known.length + " session(s): " + known.join(", ")));
      per.appendChild(r);
    });
    host.appendChild(per);

    if (unknown.length) {
      var u = el("section", "teamsec");
      u.appendChild(el("h3", null, "Codes not in this catalog"));
      u.appendChild(el("p", "teamhint", unknown.join(", ")
        + " — either a typo, or sessions AWS has since withdrawn."));
      host.appendChild(u);
    }
  }


  /* ---- what AWS just shipped, and who is covering it -------------------
     re:Invent week is when AWS ships everything, and the question on the
     Tuesday is not "what sessions exist" but "they announced that at the
     keynote -- is anyone covering it?". The announcement store already
     exists on this site and is refreshed daily, so this is a join, not a
     new pipeline.

     The join is by SERVICE, which is honest but coarse: it says "this
     announcement and these sessions are about the same service", not
     "this session covers this announcement". The wording says so, because
     a session scheduled in September cannot be about a launch made in
     December -- and during the event, that is exactly the overlap worth
     looking at anyway. */
  function renderNews() {
    var host = $("#newsbody");
    if (!host) return;
    host.textContent = "";
    var items = CFG.news || [];
    if (!items.length) {
      host.appendChild(el("p", "empty",
        "No recent AWS announcements line up with a service in this "
        + "catalog."));
      return;
    }

    var byService = {};
    DATA.sessions.forEach(function (sn) {
      sn.sv.forEach(function (i) {
        (byService[i] = byService[i] || []).push(sn);
      });
    });

    var head = el("p", "count");
    head.innerHTML = "<b>" + items.length + "</b> AWS announcement"
      + (items.length === 1 ? "" : "s") + " from the last few weeks that "
      + "name a service this catalog also covers";
    host.appendChild(head);

    items.forEach(function (a) {
      var box = el("article", "newsitem");
      var top = el("div", "top");
      top.appendChild(el("span", "code", a.d));
      a.sv.forEach(function (i) {
        top.appendChild(el("span", "tag", DATA.facets.Services[i]));
      });
      box.appendChild(top);

      var t = el("p", "newstitle", a.t);
      box.appendChild(t);

      var hits = [];
      a.sv.forEach(function (i) {
        (byService[i] || []).forEach(function (sn) {
          if (hits.indexOf(sn) === -1) hits.push(sn);
        });
      });
      var line = el("div", "where");
      /* A service with hundreds of sessions cannot be pointed at. Bedrock
         has 322, so "322 sessions on the same service" followed by eight
         arbitrary codes is noise wearing the shape of a recommendation.
         Say the service is too broad and send them to the filter instead. */
      var TOO_BROAD = 40;
      if (!hits.length) {
        line.textContent = "No sessions on that service.";
      } else if (hits.length > TOO_BROAD) {
        line.textContent = hits.length + " sessions carry that service — "
          + "too many to single any out. ";
        var jump = el("a", "hoplink", "Filter to it in Browse →");
        jump.href = "#";
        jump.addEventListener("click", function (ev) {
          ev.preventDefault();
          state.service = String(a.sv[0]);
          state.lane = "all"; state.q = ""; shown = PAGE_SIZE;
          $("#q").value = "";
          buildFilters(); view("browse"); render();
          window.scrollTo({ top: 0, behavior: "smooth" });
        });
        line.appendChild(jump);
      } else {
        line.textContent = hits.length + " session"
          + (hits.length === 1 ? "" : "s") + " on the same service: ";
        hits.slice(0, 8).forEach(function (sn, i) {
          if (i) line.appendChild(document.createTextNode(", "));
          var lk = el("a", "code", sn.c);
          lk.href = "#";
          lk.title = sn.t;
          lk.addEventListener("click", function (ev) {
            ev.preventDefault();
            state.q = sn.c; state.lane = "all"; shown = PAGE_SIZE;
            $("#q").value = sn.c;
            view("browse"); render();
            window.scrollTo({ top: 0, behavior: "smooth" });
          });
          line.appendChild(lk);
        });
        if (hits.length > 8)
          line.appendChild(document.createTextNode(
            " and " + (hits.length - 8) + " more"));
      }
      box.appendChild(line);

      if (a.u) {
        var src = el("a", "hoplink", "the announcement ↗");
        src.href = a.u; src.target = "_blank"; src.rel = "noopener";
        box.appendChild(src);
      }
      host.appendChild(box);
    });
  }

  /* ---- filters ------------------------------------------------------- */
  function buildFilters() {
    var host = $("#filters");
    host.textContent = "";

    function pick(key, label, options, valueOf) {
      var sel = el("select");
      sel.setAttribute("aria-label", label);
      sel.appendChild(new Option(label, ""));
      options.forEach(function (o) {
        sel.appendChild(new Option(o.label, o.value));
      });
      sel.value = state[key];
      sel.addEventListener("change", function () {
        state[key] = sel.value; shown = PAGE_SIZE; render();
      });
      host.appendChild(sel);
    }

    pick("day", "Any day", CFG.days.map(function (d) {
      return { label: dayLabel(d), value: d };
    }));
    pick("type", "Any format", DATA.facets.Type.map(function (t) {
      return { label: t, value: t };
    }));
    pick("level", "Any level", DATA.facets.Level.slice().sort()
      .map(function (l) { return { label: l, value: l }; }));
    pick("venue", "Any venue", DATA.venues.slice().sort()
      .map(function (v) { return { label: v, value: v }; }));

    /* Services is the long one -- 169 entries -- so it is sorted by how
       many sessions carry it, not alphabetically. The head of that list
       is what people are actually looking for. */
    var count = {};
    DATA.sessions.forEach(function (s) {
      s.sv.forEach(function (i) { count[i] = (count[i] || 0) + 1; });
    });
    var svc = Object.keys(count).map(Number).sort(function (a, b) {
      return count[b] - count[a];
    }).map(function (i) {
      return { label: DATA.facets.Services[i] + "  (" + count[i] + ")",
               value: String(i) };
    });
    pick("service", "Any service", svc);
  }

  function renderChips() {
    var host = $("#chips");
    host.textContent = "";
    var live = [];
    if (state.lane !== "all")
      live.push(["lane", laneName(state.lane)]);
    [["day", state.day && dayLabel(state.day)],
     ["type", state.type], ["level", state.level], ["venue", state.venue],
     ["service", state.service &&
       DATA.facets.Services[+state.service]]].forEach(function (p) {
      if (p[1]) live.push(p);
    });
    live.forEach(function (p) {
      var chip = el("span", "chip", p[1]);
      var x = el("button", null, "×");
      x.title = "Remove this filter";
      x.addEventListener("click", function () {
        state[p[0]] = p[0] === "lane" ? "all" : "";
        shown = PAGE_SIZE; buildFilters(); render();
      });
      chip.appendChild(x);
      host.appendChild(chip);
    });
  }

  function syncLaneTabs() {
    Array.prototype.forEach.call(
      document.querySelectorAll(".lane"), function (b) {
        b.setAttribute("aria-pressed",
          b.dataset.lane === state.lane ? "true" : "false");
      });
  }

  function render() {
    syncLaneTabs(); renderChips(); renderBrowse(); syncStars();
    $("#clear").hidden = !state.q;
    if (!$("#map").hidden) renderMap();
  }

  /* ---- wiring -------------------------------------------------------- */
  function wire() {
    Array.prototype.forEach.call(
      document.querySelectorAll(".lane"), function (b) {
        b.addEventListener("click", function () {
          state.lane = b.dataset.lane; shown = PAGE_SIZE; render();
          window.scrollTo({ top: $(".controls").offsetTop - 12,
                            behavior: "smooth" });
        });
      });

    var timer = null;
    $("#q").addEventListener("input", function (e) {
      clearTimeout(timer);
      var v = e.target.value;
      timer = setTimeout(function () {
        state.q = v.trim(); shown = PAGE_SIZE; render();
      }, 140);
    });
    $("#clear").addEventListener("click", function () {
      $("#q").value = ""; state.q = ""; shown = PAGE_SIZE; render();
    });

    $("#tab-browse").addEventListener("click", function () { view("browse"); });
    $("#tab-plan").addEventListener("click", function () { view("plan"); });
    $("#tab-map").addEventListener("click", function () { view("map"); });
    $("#tab-now").addEventListener("click", function () { view("now"); });
    $("#tab-team").addEventListener("click", function () { view("team"); });
    $("#tab-news").addEventListener("click", function () { view("news"); });

    var teamTimer = null;
    $("#teamin").addEventListener("input", function () {
      clearTimeout(teamTimer);
      teamTimer = setTimeout(function () {
        save(TEAM_KEY, $("#teamin").value);
        renderTeam();
      }, 250);
    });

    $("#share").addEventListener("click", function () {
      var url = location.origin + location.pathname +
        "#plan=" + encodeURIComponent(plan.join(","));
      var done = function () { $("#share").textContent = "Link copied";
        setTimeout(function () {
          $("#share").textContent = "Copy a link to this plan"; }, 1800); };
      if (navigator.clipboard) navigator.clipboard.writeText(url).then(done, done);
      else { prompt("Copy this link", url); }
    });

    $("#verify").addEventListener("click", verifyPlan);

    $("#ics").addEventListener("click", function () {
      var cal = buildICS();
      if (!cal.count) { alert("Star some sessions first."); return; }
      download("reinvent-2026.ics", cal.text, "text/calendar");
    });

    $("#md").addEventListener("click", function () {
      if (!plan.length) { alert("Star some sessions first."); return; }
      download("reinvent-2026-notes.md", buildMarkdown(), "text/markdown");
    });

    $("#wipe").addEventListener("click", function () {
      if (!plan.length) return;
      if (!confirm("Clear all " + plan.length + " starred sessions?")) return;
      plan = []; save(PLAN_KEY, plan); syncStars(); renderPlan();
    });

    var over = $("#t-overhead"), pace = $("#t-pace");
    over.value = tune.overhead;
    pace.value = String(tune.pace);
    over.addEventListener("change", function () {
      var v = parseInt(over.value, 10);
      if (isNaN(v) || v < 0) { over.value = tune.overhead; return; }
      tune.overhead = v; save(TUNE_KEY, tune); renderPlan(); renderMatrix();
    });
    pace.addEventListener("change", function () {
      tune.pace = parseInt(pace.value, 10) || CFG.travel.pace;
      save(TUNE_KEY, tune); renderPlan(); renderMatrix();
    });
  }

  function view(which) {
    $("#browse").hidden = which !== "browse";
    $("#plan").hidden = which !== "plan";
    $("#map").hidden = which !== "map";
    $("#now").hidden = which !== "now";
    $("#team").hidden = which !== "team";
    $("#news").hidden = which !== "news";
    /* Search, filters and lanes drive Browse AND the map's heat, so they
       stay up for both. In the plan they are dead controls that push the
       plan below the fold -- on a phone, past it entirely. */
    var showControls = (which === "browse" || which === "map");
    $(".controls").hidden = !showControls;
    document.querySelector(".lanes").hidden = !showControls;
    [["#tab-browse", "browse"], ["#tab-plan", "plan"], ["#tab-map", "map"],
     ["#tab-now", "now"], ["#tab-team", "team"],
     ["#tab-news", "news"]]
      .forEach(function (p) {
        $(p[0]).setAttribute("aria-selected",
                             which === p[1] ? "true" : "false");
      });
    if (which === "plan") renderPlan();
    if (which === "map") { fillMapDays(); renderMap(); }
    if (which === "now") { fillNowControls(); renderNow(); }
    if (which === "team") {
      var ta = $("#teamin");
      if (ta && !ta.value) ta.value = load(TEAM_KEY, "") || "";
      renderTeam();
    }
    if (which === "news") renderNews();
  }

  function adoptSharedPlan() {
    var m = /[#&]plan=([^&]*)/.exec(location.hash);
    if (!m) return false;
    var codes = decodeURIComponent(m[1]).split(",").filter(Boolean);
    if (!codes.length) return false;
    plan = codes; save(PLAN_KEY, plan);
    history.replaceState(null, "", location.pathname);
    return true;
  }

  /* ---- boot ---------------------------------------------------------- */
  /* ---- offline ---------------------------------------------------------
     The site already has a service worker at /sw.js with scope "/", and its
     strategies happen to be exactly right for this page: navigations and
     CSS/JS are stale-while-revalidate, and everything else -- which is where
     the catalog JSON lands -- is network-first with a cache fallback. So a
     page that has been opened once keeps working when the wifi dies in a
     keynote hall, which it will.

     What was missing is the registration. site-footer.js does it for the
     rest of the site and this page is self-contained, so a teammate handed
     only this link would never have registered anything and would have got
     no offline at all. One line, guarded, and failure is silent: offline is
     a bonus, not a dependency. */
  if ("serviceWorker" in navigator) {
    window.addEventListener("load", function () {
      navigator.serviceWorker.register("/sw.js").catch(function () {});
    });
  }

  fetch("/intelligence/reinvent2026.json")
    .then(function (r) {
      if (!r.ok) throw new Error("HTTP " + r.status);
      return r.json();
    })
    .then(function (d) {
      DATA = d;
      var shared = adoptSharedPlan();
      /* A shared link opened while the page is already up changes only the
         fragment, which is a same-document navigation -- no reload, so the
         boot path below never runs again. Without this, a teammate clicking
         someone's plan link from this very page sees nothing happen. */
      window.addEventListener("hashchange", function () {
        if (adoptSharedPlan()) { syncStars(); renderPlan(); view("plan"); }
      });
      var all = document.querySelector('[data-count="all"]');
      if (all) all.textContent = DATA.sessions.length.toLocaleString();
      buildFilters(); wire(); renderFreshness(); renderMatrix();
      checkLive();
      render();
      if (shared) view("plan");
    })
    .catch(function (err) {
      $("#count").textContent =
        "The session data did not load (" + err.message +
        "). The official catalog still works.";
    });
})();
