/* Generated by scripts/build_reinvent_page.py -- do not edit by hand. */
(function () {
  "use strict";
  var CFG = window.RI_CONFIG, DATA = null;
  var PAGE_SIZE = 60, shown = PAGE_SIZE;
  var PLAN_KEY = "ri2026.plan", TUNE_KEY = "ri2026.travel";
  var CATALOG_URL = "https://registration.awsevents.com/flow/awsevents/"
                  + "reinvent2026/eventcatalog/page/eventcatalog";

  var state = { lane: "all", q: "", day: "", type: "", level: "",
                venue: "", service: "" };
  var plan = load(PLAN_KEY, []);
  var tune = load(TUNE_KEY, null) || {
    same: CFG.travel.same, near: CFG.travel.near, far: CFG.travel.far };

  function load(key, dflt) {
    try { var v = JSON.parse(localStorage.getItem(key)); return v || dflt; }
    catch (e) { return dflt; }
  }
  function save(key, value) {
    try { localStorage.setItem(key, JSON.stringify(value)); } catch (e) {}
  }
  function $(sel) { return document.querySelector(sel); }
  function el(tag, cls, text) {
    var n = document.createElement(tag);
    if (cls) n.className = cls;
    if (text != null) n.textContent = text;
    return n;
  }
  function hhmm(min) {
    var h = Math.floor(min / 60), m = min % 60;
    return (h < 10 ? "0" : "") + h + ":" + (m < 10 ? "0" : "") + m;
  }
  function dayLabel(iso) {
    var d = new Date(iso + "T12:00:00");
    return d.toLocaleDateString(undefined,
      { weekday: "long", day: "numeric", month: "long" });
  }

  /* ---- the venue-hop rule -------------------------------------------
     The gap is a fact from AWS's own times. `need` is this page's
     estimate, and the two are reported separately in the wording. */
  function needFor(fromVenue, toVenue) {
    if (fromVenue === toVenue) return tune.same;
    var outlier = CFG.travel.outlier;
    if (fromVenue === outlier || toVenue === outlier) return tune.far;
    return tune.near;
  }

  /* ---- data --------------------------------------------------------- */
  function firstSlot(s) { return s.when && s.when.length ? s.when[0] : null; }
  function svcNames(s) {
    return s.sv.map(function (i) { return DATA.facets.Services[i]; });
  }
  function typeName(s) {
    return s.ty == null ? "" : DATA.facets.Type[s.ty];
  }
  function levelName(s) {
    return s.lv == null ? "" : DATA.facets.Level[s.lv];
  }
  function venueName(slot) { return DATA.venues[slot.v]; }
  function roomName(slot) { return DATA.rooms[slot.r]; }

  function laneServices(id) {
    for (var i = 0; i < CFG.lanes.length; i++)
      if (CFG.lanes[i].id === id) return CFG.lanes[i].services;
    return null;
  }

  function matches(s) {
    if (state.lane !== "all") {
      var want = laneServices(state.lane), hit = false;
      for (var i = 0; i < s.sv.length && !hit; i++)
        if (want.indexOf(s.sv[i]) !== -1) hit = true;
      if (!hit) return false;
    }
    if (state.type && typeName(s) !== state.type) return false;
    if (state.level && levelName(s) !== state.level) return false;
    if (state.service && s.sv.indexOf(+state.service) === -1) return false;
    if (state.day || state.venue) {
      var ok = false;
      for (var j = 0; j < s.when.length && !ok; j++) {
        var w = s.when[j];
        if (state.day && w.d !== state.day) continue;
        if (state.venue && venueName(w) !== state.venue) continue;
        ok = true;
      }
      if (!ok) return false;
    }
    if (state.q) {
      var hay = (s.c + " " + s.t + " " + s.a + " " +
                 svcNames(s).join(" ")).toLowerCase();
      var terms = state.q.toLowerCase().split(/\s+/);
      for (var k = 0; k < terms.length; k++)
        if (terms[k] && hay.indexOf(terms[k]) === -1) return false;
    }
    return true;
  }

  function filtered() { return DATA.sessions.filter(matches); }

  /* ---- rendering ----------------------------------------------------- */
  function card(s, slot) {
    var c = el("article", "card");
    c.dataset.code = s.c;

    var top = el("div", "top");
    /* The code is the link. ?search=<code> was verified against a control:
       the /sessionDetails?sessionId= form silently falls back to the full
       catalog list, which looks like it worked. This one resolves, and the
       code is stable and human-readable where the internal id is neither. */
    var code = el("a", "code", s.c);
    code.href = CATALOG_URL + "?search=" + encodeURIComponent(s.c);
    code.target = "_blank";
    code.rel = "noopener";
    code.title = "Open " + s.c + " in the official AWS catalog";
    top.appendChild(code);
    if (typeName(s)) top.appendChild(el("span", "tag", typeName(s)));
    if (levelName(s)) top.appendChild(el("span", "tag lvl", levelName(s)));
    if (slot && slot.e != null) {
      top.appendChild(el("span", "tag",
        hhmm(slot.b) + "–" + hhmm(slot.e)));
    } else if (slot) {
      /* AWS publishes a start and no duration for a few sponsored
         sessions. Saying so beats inventing an end time. */
      top.appendChild(el("span", "tag",
        hhmm(slot.b) + " · length not published"));
    } else {
      top.appendChild(el("span", "tag", "not yet scheduled"));
    }
    c.appendChild(top);

    c.appendChild(el("h3", null, s.t));

    var where = el("div", "where");
    if (slot) {
      var b = el("b", null, venueName(slot));
      where.appendChild(b);
      var rest = roomName(slot).split("|").slice(1).join(" · ").trim();
      where.appendChild(document.createTextNode(
        (rest ? " · " + rest : "") +
        (slot.cap ? " · " + slot.cap + " seats" : "")));
    } else {
      where.textContent = "Venue to be announced";
    }
    c.appendChild(where);

    var star = el("button", "star", inPlan(s.c) ? "★" : "☆");
    star.setAttribute("aria-pressed", inPlan(s.c) ? "true" : "false");
    star.title = inPlan(s.c) ? "Remove from my plan" : "Add to my plan";
    star.addEventListener("click", function () { toggle(s.c); });
    c.appendChild(star);

    if (s.a) {
      var more = el("button", "more", "What is in it ›");
      var abs = el("p", "abstract", s.a);
      if (svcNames(s).length)
        abs.appendChild(el("span", null, "\n\nServices: " +
          svcNames(s).join(", ")));
      more.addEventListener("click", function () {
        c.classList.toggle("open");
        more.textContent = c.classList.contains("open")
          ? "Hide ‹" : "What is in it ›";
      });
      c.appendChild(more);
      c.appendChild(abs);
    }
    return c;
  }

  function renderBrowse() {
    var box = $("#browse");
    box.textContent = "";
    var list = filtered();

    $("#count").innerHTML = "<b>" + list.length.toLocaleString() +
      "</b> session" + (list.length === 1 ? "" : "s") +
      (state.lane === "all" ? "" : " in " + laneName(state.lane));

    if (!list.length) {
      box.appendChild(el("p", "empty",
        "Nothing matches. Try clearing a filter."));
      return;
    }

    /* One row per scheduled slot, so a repeated session appears on each
       day it actually runs -- which is the thing you are choosing between. */
    var rows = [];
    list.forEach(function (s) {
      if (!s.when.length) { rows.push({ s: s, w: null, d: "zzz" }); return; }
      s.when.forEach(function (w) {
        if (state.day && w.d !== state.day) return;
        if (state.venue && venueName(w) !== state.venue) return;
        rows.push({ s: s, w: w, d: w.d });
      });
    });
    rows.sort(function (a, b) {
      if (a.d !== b.d) return a.d < b.d ? -1 : 1;
      if (!a.w || !b.w) return a.w ? -1 : 1;
      return a.w.b - b.w.b;
    });

    var slice = rows.slice(0, shown), group = null, host = null;
    slice.forEach(function (r) {
      if (r.d !== group) {
        group = r.d;
        var g = el("section", "daygroup");
        g.appendChild(el("h2", "dayhead",
          r.w ? dayLabel(r.d) : "Not yet scheduled"));
        box.appendChild(g);
        host = g;
      }
      host.appendChild(card(r.s, r.w));
    });

    if (rows.length > shown) {
      var pager = el("div", "pager");
      var btn = el("button", "ghost",
        "Show " + Math.min(PAGE_SIZE, rows.length - shown) + " more of " +
        (rows.length - shown).toLocaleString());
      btn.addEventListener("click", function () {
        shown += PAGE_SIZE; renderBrowse();
      });
      pager.appendChild(btn);
      box.appendChild(pager);
    }
  }

  /* ---- how old is this, really ---------------------------------------
     Computed here rather than written in at build time, because the
     honest number is the one the reader is looking at now. A page built
     in September and opened in November has not got fresher, and a
     baked-in "captured 22 Sep" invites it to be read as if it had. */
  var AGING_DAYS = 10, STALE_DAYS = 21;

  function daysSince(iso) {
    if (!iso) return null;
    var then = new Date(iso);
    if (isNaN(then.getTime())) return null;
    return Math.floor((Date.now() - then.getTime()) / 86400000);
  }

  function renderFreshness() {
    var box = $("#fresh");
    var age = daysSince(DATA.captured_utc || DATA.captured);
    var when = DATA.captured || "an unrecorded date";
    box.textContent = "";

    if (age === null) {
      box.className = "fresh stale";
      box.appendChild(el("span", null,
        "This copy of the catalog carries no capture date, so there is no "
        + "way to tell how old it is. Treat every time and room here as "
        + "unconfirmed and check the official catalog."));
      addCatalogLink(box);
      return;
    }

    var howLong = age === 0 ? "earlier today"
                : age === 1 ? "yesterday"
                : age + " days ago";
    var b = el("b", null, "Catalog checked " + howLong);
    box.appendChild(b);

    if (age >= STALE_DAYS) {
      box.className = "fresh stale";
      box.appendChild(el("span", null,
        " (" + when + "). That is old enough that sessions have probably "
        + "been added, moved or cancelled since. Confirm anything you are "
        + "relying on — every card links to its entry in the "));
      addCatalogLink(box);
    } else if (age >= AGING_DAYS) {
      box.className = "fresh aging";
      box.appendChild(el("span", null,
        " (" + when + "). Sessions move as the event gets closer, so check "
        + "anything you are relying on against the "));
      addCatalogLink(box);
    } else {
      box.className = "fresh good";
      box.appendChild(el("span", null,
        " (" + when + "), against " + DATA.sessions.length.toLocaleString()
        + " sessions. Seat reservations and last-minute changes still live "
        + "in the "));
      addCatalogLink(box);
    }
  }

  function addCatalogLink(box) {
    var a = el("a", null, "official catalog");
    a.href = CATALOG_URL;
    a.target = "_blank";
    a.rel = "noopener";
    box.appendChild(a);
    box.appendChild(document.createTextNode("."));
  }

  function laneName(id) {
    for (var i = 0; i < CFG.lanes.length; i++)
      if (CFG.lanes[i].id === id) return CFG.lanes[i].name;
    return id;
  }

  /* ---- the plan ------------------------------------------------------ */
  function inPlan(code) { return plan.indexOf(code) !== -1; }
  function toggle(code) {
    var i = plan.indexOf(code);
    if (i === -1) plan.push(code); else plan.splice(i, 1);
    save(PLAN_KEY, plan);
    syncStars(); renderPlan();
  }
  function syncStars() {
    $("#planN").textContent = plan.length;
    Array.prototype.forEach.call(
      document.querySelectorAll(".card"), function (c) {
        var on = inPlan(c.dataset.code), b = c.querySelector(".star");
        if (!b) return;
        b.textContent = on ? "★" : "☆";
        b.setAttribute("aria-pressed", on ? "true" : "false");
        b.title = on ? "Remove from my plan" : "Add to my plan";
      });
  }

  function planRows() {
    var by = {}, rows = [];
    DATA.sessions.forEach(function (s) { by[s.c] = s; });
    plan.forEach(function (code) {
      var s = by[code];
      if (!s) {
        /* The session is starred and is no longer in the catalog. Dropping
           it silently was the worst thing this page could do: the plan
           would simply be one session shorter than the person built, with
           nothing to say a talk they were counting on has gone. */
        rows.push({ gone: code, d: "zzzz" });
        return;
      }
      if (!s.when.length) { rows.push({ s: s, w: null, d: "zzz" }); return; }
      s.when.forEach(function (w) { rows.push({ s: s, w: w, d: w.d }); });
    });
    rows.sort(function (a, b) {
      if (a.d !== b.d) return a.d < b.d ? -1 : 1;
      if (!a.w || !b.w) return a.w ? -1 : 1;
      return a.w.b - b.w.b;
    });
    return rows;
  }

  function renderPlan() {
    var box = $("#planbody");
    box.textContent = "";
    var rows = planRows();
    if (!rows.length) {
      box.appendChild(el("p", "empty",
        "Nothing starred yet. Star a session in Browse and it lands here, "
        + "with the travel between them checked."));
      return;
    }

    var group = null, host = null, prev = null;
    rows.forEach(function (r) {
      if (r.d !== group) {
        group = r.d; prev = null;
        host = el("section", "daygroup");
        host.appendChild(el("h2", "dayhead",
          r.gone ? "No longer in the catalog"
                 : r.w ? dayLabel(r.d) : "Not yet scheduled"));
        box.appendChild(host);
      }
      if (r.gone) { host.appendChild(goneCard(r.gone)); prev = null; return; }
      if (prev && prev.w && r.w) host.appendChild(gapRow(prev, r));
      host.appendChild(card(r.s, r.w));
      prev = r;
    });
  }

  function goneCard(code) {
    var c = el("article", "card gone");
    c.dataset.code = code;
    var top = el("div", "top");
    top.appendChild(el("span", "code", code));
    top.appendChild(el("span", "tag", "withdrawn or renamed"));
    c.appendChild(top);
    c.appendChild(el("h3", null, "This session is no longer in the catalog"));
    var where = el("div", "where");
    where.appendChild(document.createTextNode(
      "You starred it, and the capture of " + (DATA.captured || "the catalog")
      + " does not contain it. AWS may have withdrawn, merged or renumbered "
      + "it. Check "));
    var a = el("a", null, code + " in the official catalog");
    a.href = CATALOG_URL + "?search=" + encodeURIComponent(code);
    a.target = "_blank"; a.rel = "noopener";
    where.appendChild(a);
    where.appendChild(document.createTextNode("."));
    c.appendChild(where);
    var drop = el("button", "star", "×");
    drop.title = "Remove it from my plan";
    drop.addEventListener("click", function () { toggle(code); });
    c.appendChild(drop);
    return c;
  }

  function gapRow(a, b) {
    var from = venueName(a.w), to = venueName(b.w);
    var need = needFor(from, to);
    var row = el("div", "gap"), msg;

    if (a.w.e == null) {
      /* No published end, so there is no gap to measure. The page says
         that rather than measuring from the start time and calling the
         result a gap -- which would under-warn on exactly the hop this
         feature exists to catch. */
      row.className = "gap warn";
      row.appendChild(el("span", "ic", "○"));
      row.appendChild(el("span", null,
        "AWS does not publish how long " + a.s.c + " runs, so the time "
        + "before " + b.s.c + " cannot be checked."
        + (from === to ? "" : " They are at different properties — "
           + from + " to " + to + " — so allow about " + need + " min.")));
      return row;
    }

    var gap = b.w.b - a.w.e;
    if (gap < 0) {
      row.className = "gap bad";
      row.appendChild(el("span", "ic", "●"));
      msg = "These overlap by " + (-gap) + " min. " +
        (from === to ? "Same property, but you cannot be in both."
                     : from + " and " + to + " at once is not possible.");
    } else if (gap < need) {
      row.className = "gap warn";
      row.appendChild(el("span", "ic", "●"));
      msg = gap + " min between them" +
        (from === to ? " inside " + from
                     : ", and they are at different properties — " +
                       from + " to " + to) +
        ". Allow about " + need + ". You would be late.";
    } else {
      row.className = "gap ok";
      row.appendChild(el("span", "ic", "○"));
      msg = gap + " min" +
        (from === to ? " to change rooms inside " + from
                     : " to get from " + from + " to " + to) + ".";
    }
    row.appendChild(el("span", null, msg));
    return row;
  }

  /* ---- filters ------------------------------------------------------- */
  function buildFilters() {
    var host = $("#filters");
    host.textContent = "";

    function pick(key, label, options, valueOf) {
      var sel = el("select");
      sel.setAttribute("aria-label", label);
      sel.appendChild(new Option(label, ""));
      options.forEach(function (o) {
        sel.appendChild(new Option(o.label, o.value));
      });
      sel.value = state[key];
      sel.addEventListener("change", function () {
        state[key] = sel.value; shown = PAGE_SIZE; render();
      });
      host.appendChild(sel);
    }

    pick("day", "Any day", CFG.days.map(function (d) {
      return { label: dayLabel(d), value: d };
    }));
    pick("type", "Any format", DATA.facets.Type.map(function (t) {
      return { label: t, value: t };
    }));
    pick("level", "Any level", DATA.facets.Level.slice().sort()
      .map(function (l) { return { label: l, value: l }; }));
    pick("venue", "Any venue", DATA.venues.slice().sort()
      .map(function (v) { return { label: v, value: v }; }));

    /* Services is the long one -- 169 entries -- so it is sorted by how
       many sessions carry it, not alphabetically. The head of that list
       is what people are actually looking for. */
    var count = {};
    DATA.sessions.forEach(function (s) {
      s.sv.forEach(function (i) { count[i] = (count[i] || 0) + 1; });
    });
    var svc = Object.keys(count).map(Number).sort(function (a, b) {
      return count[b] - count[a];
    }).map(function (i) {
      return { label: DATA.facets.Services[i] + "  (" + count[i] + ")",
               value: String(i) };
    });
    pick("service", "Any service", svc);
  }

  function renderChips() {
    var host = $("#chips");
    host.textContent = "";
    var live = [];
    if (state.lane !== "all")
      live.push(["lane", laneName(state.lane)]);
    [["day", state.day && dayLabel(state.day)],
     ["type", state.type], ["level", state.level], ["venue", state.venue],
     ["service", state.service &&
       DATA.facets.Services[+state.service]]].forEach(function (p) {
      if (p[1]) live.push(p);
    });
    live.forEach(function (p) {
      var chip = el("span", "chip", p[1]);
      var x = el("button", null, "×");
      x.title = "Remove this filter";
      x.addEventListener("click", function () {
        state[p[0]] = p[0] === "lane" ? "all" : "";
        shown = PAGE_SIZE; buildFilters(); render();
      });
      chip.appendChild(x);
      host.appendChild(chip);
    });
  }

  function syncLaneTabs() {
    Array.prototype.forEach.call(
      document.querySelectorAll(".lane"), function (b) {
        b.setAttribute("aria-pressed",
          b.dataset.lane === state.lane ? "true" : "false");
      });
  }

  function render() {
    syncLaneTabs(); renderChips(); renderBrowse(); syncStars();
    $("#clear").hidden = !state.q;
  }

  /* ---- wiring -------------------------------------------------------- */
  function wire() {
    Array.prototype.forEach.call(
      document.querySelectorAll(".lane"), function (b) {
        b.addEventListener("click", function () {
          state.lane = b.dataset.lane; shown = PAGE_SIZE; render();
          window.scrollTo({ top: $(".controls").offsetTop - 12,
                            behavior: "smooth" });
        });
      });

    var timer = null;
    $("#q").addEventListener("input", function (e) {
      clearTimeout(timer);
      var v = e.target.value;
      timer = setTimeout(function () {
        state.q = v.trim(); shown = PAGE_SIZE; render();
      }, 140);
    });
    $("#clear").addEventListener("click", function () {
      $("#q").value = ""; state.q = ""; shown = PAGE_SIZE; render();
    });

    $("#tab-browse").addEventListener("click", function () { view("browse"); });
    $("#tab-plan").addEventListener("click", function () { view("plan"); });

    $("#share").addEventListener("click", function () {
      var url = location.origin + location.pathname +
        "#plan=" + encodeURIComponent(plan.join(","));
      var done = function () { $("#share").textContent = "Link copied";
        setTimeout(function () {
          $("#share").textContent = "Copy a link to this plan"; }, 1800); };
      if (navigator.clipboard) navigator.clipboard.writeText(url).then(done, done);
      else { prompt("Copy this link", url); }
    });

    $("#wipe").addEventListener("click", function () {
      if (!plan.length) return;
      if (!confirm("Clear all " + plan.length + " starred sessions?")) return;
      plan = []; save(PLAN_KEY, plan); syncStars(); renderPlan();
    });

    [["#t-same", "same"], ["#t-near", "near"], ["#t-far", "far"]]
      .forEach(function (p) {
        var input = $(p[0]);
        input.value = tune[p[1]];
        input.addEventListener("change", function () {
          var v = parseInt(input.value, 10);
          if (isNaN(v) || v < 0) { input.value = tune[p[1]]; return; }
          tune[p[1]] = v; save(TUNE_KEY, tune); renderPlan();
        });
      });
  }

  function view(which) {
    var browsing = which === "browse";
    $("#browse").hidden = !browsing;
    $("#plan").hidden = browsing;
    /* Search, filters and lanes only act on Browse. Left visible in the
       plan they are dead controls that push the plan itself below the
       fold -- on a phone, past it entirely. */
    $(".controls").hidden = !browsing;
    document.querySelector(".lanes").hidden = !browsing;
    $("#tab-browse").setAttribute("aria-selected", browsing ? "true" : "false");
    $("#tab-plan").setAttribute("aria-selected", browsing ? "false" : "true");
    if (!browsing) renderPlan();
  }

  function adoptSharedPlan() {
    var m = /[#&]plan=([^&]*)/.exec(location.hash);
    if (!m) return false;
    var codes = decodeURIComponent(m[1]).split(",").filter(Boolean);
    if (!codes.length) return false;
    plan = codes; save(PLAN_KEY, plan);
    history.replaceState(null, "", location.pathname);
    return true;
  }

  /* ---- boot ---------------------------------------------------------- */
  fetch("/intelligence/reinvent2026.json")
    .then(function (r) {
      if (!r.ok) throw new Error("HTTP " + r.status);
      return r.json();
    })
    .then(function (d) {
      DATA = d;
      var shared = adoptSharedPlan();
      /* A shared link opened while the page is already up changes only the
         fragment, which is a same-document navigation -- no reload, so the
         boot path below never runs again. Without this, a teammate clicking
         someone's plan link from this very page sees nothing happen. */
      window.addEventListener("hashchange", function () {
        if (adoptSharedPlan()) { syncStars(); renderPlan(); view("plan"); }
      });
      var all = document.querySelector('[data-count="all"]');
      if (all) all.textContent = DATA.sessions.length.toLocaleString();
      buildFilters(); wire(); renderFreshness(); render();
      if (shared) view("plan");
    })
    .catch(function (err) {
      $("#count").textContent =
        "The session data did not load (" + err.message +
        "). The official catalog still works.";
    });
})();
