#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Rebase, resolve the generated files, and push. Retry until it lands.

    python scripts/push_retry.py            # up to 5 attempts
    python scripts/push_retry.py --attempts 8

Why this exists
---------------
Four windows share one repository and one branch. A post is five files that
belong to nobody else -- its source, its diagram, its built page -- and twenty
that every window rewrites on every post: blog/index.html, blog/page/2..11,
cards.json, posts.json, stats.json, rss.xml, sitemap.xml, how-this-was-made.

Those twenty are build output. sync_blog.py regenerates all of them from
posts/ alone, which is why the resolution is never a judgement call: take any
version, re-run the build, and the result is correct by construction. The
files that are genuinely one author's have never conflicted once.

So every push goes the same way, and it went this way four times on the
evening of 2026-09-19 for Azure #38 and Weekly #6:

    push  -> rejected, main moved while the pre-push gate ran 5-10 minutes
    fetch -> rebase -> 17 conflicts, all of them generated
    take theirs, run sync_blog, fix_series_nav, continue
    push  -> rejected again, because that took another 5-10 minutes

Done by hand that is twenty minutes of mechanical work per post, and it is
worse than mechanical: an earlier inline retry loop bailed on the first
conflict and left the worktree mid-rebase with a post file missing from disk.
Recovering that needed `git rebase --abort` and a careful check that both
commits survived. A loop that cannot resolve conflicts should not be driving
a rebase.

This is not the real fix. The real fix is to stop committing build output at
all -- let each window commit only its own five files, and have CI run
sync_blog.py and commit the index. Then no two windows ever touch the same
file and the conflicts stop existing rather than being handled. That change
belongs to whoever owns the shared build, so this script makes the current
arrangement survivable in the meantime.
"""
import argparse
import os
import subprocess
import sys

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Regenerated by sync_blog.py from posts/. A conflict here is not a
# disagreement about content, it is two windows having built the same file
# from different inputs -- so the resolution is to rebuild, never to merge.
# Matched as prefixes against the conflicted path.
GENERATED = (
    "blog/", "sitemap.xml", "robots.txt", "how-this-was-made/",
    "intelligence/", "index.html", "now.html", "resume.html", "sw.js",
)


def run(*cmd, **kw):
    p = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True,
                       encoding="utf-8", errors="replace", **kw)
    return p.returncode, (p.stdout or "") + (p.stderr or "")


def conflicted():
    _, out = run("git", "diff", "--name-only", "--diff-filter=U")
    return [l.strip() for l in out.splitlines() if l.strip()]


def rebasing():
    _, d = run("git", "rev-parse", "--git-dir")
    d = d.strip()
    return any(os.path.isdir(os.path.join(ROOT, d, x))
               for x in ("rebase-merge", "rebase-apply"))


def resolve_generated():
    """Take any side of the generated files, then rebuild them properly.

    Returns False if something conflicted that is NOT generated -- a real
    conflict in a post, which a human should look at rather than a script.
    """
    files = conflicted()
    unknown = [f for f in files if not f.startswith(GENERATED)]
    if unknown:
        print("  real conflict, not generated output -- stopping:")
        for f in unknown:
            print("    %s" % f)
        return False
    for f in files:
        run("git", "checkout", "--theirs", "--", f)
        run("git", "add", "--", f)
    print("  resolved %d generated file(s); rebuilding" % len(files))
    for script, args in (("sync_blog.py", ["--skip-freshness-check"]),
                         ("fix_series_nav.py", [])):
        code, out = run(sys.executable, os.path.join("scripts", script), *args)
        print("    %-18s %s" % (script, out.strip().splitlines()[-1]
                                if out.strip() else "ok"))
    run("git", "add", "-A", ".")
    return True


def attempt(n):
    print("\nattempt %d" % n)
    run("git", "fetch", "origin", "--quiet")

    # sync_blog.py rewrites status feeds and how-this-was-made on every run,
    # and an unstaged change stops a rebase before it starts. They are
    # regenerated, so discarding is safe and keeps the tree clean enough to
    # rebase.
    run("git", "checkout", "--", "intelligence/", "how-this-was-made/")

    code, out = run("git", "rebase", "origin/main")
    while rebasing():
        if not conflicted():
            code, out = run("git", "rebase", "--continue",
                            env=dict(os.environ, GIT_EDITOR="true"))
            if rebasing() and not conflicted():
                print("  rebase stuck with nothing to resolve:\n%s" % out[-400:])
                run("git", "rebase", "--abort")
                return False
            continue
        if not resolve_generated():
            run("git", "rebase", "--abort")
            print("  aborted cleanly; your commits are intact")
            return False
        run("git", "rebase", "--continue", env=dict(os.environ,
                                                    GIT_EDITOR="true"))

    _, ahead = run("git", "rev-list", "--count", "origin/main..HEAD")
    print("  rebased, %s commit(s) to push -- running the gate" % ahead.strip())

    code, out = run("git", "push", "origin", "HEAD:main")
    if "rejected" in out or code != 0:
        why = "main moved again" if ("fetch first" in out or "lock ref" in out
                                     or "non-fast-forward" in out) else "gate"
        print("  push refused (%s)" % why)
        for line in out.strip().splitlines()[-3:]:
            print("    %s" % line)
        return False
    print("  PUSHED")
    for line in out.strip().splitlines()[-2:]:
        print("    %s" % line)
    return True


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--attempts", type=int, default=5)
    args = ap.parse_args()

    for n in range(1, args.attempts + 1):
        if attempt(n):
            return 0
    print("\n%d attempts, still not pushed. The branch is rebased and the "
          "commits are intact; nothing was lost." % args.attempts)
    return 1


if __name__ == "__main__":
    sys.exit(main())
